'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CLPCustomerView
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/", ConfigurationName:="CLPCustomerView.ClpCustomer")>  _
    Public Interface ClpCustomer
        
        'CODEGEN: Generating message contract since the operation viewCustomer is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function viewCustomer(ByVal request As CLPCustomerView.viewCustomerRequest) As CLPCustomerView.viewCustomerResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/")>  _
    Partial Public Class viewCustomer
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As clpCustomerRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As clpCustomerRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/")>  _
    Partial Public Class clpCustomerRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private customerIdField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property customerId() As String
            Get
                Return Me.customerIdField
            End Get
            Set
                Me.customerIdField = value
                Me.RaisePropertyChanged("customerId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/")>  _
    Partial Public Class clpCustomerDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private birthDateField As String
        
        Private cardNoField As String
        
        Private educationField As String
        
        Private emailIdField As String
        
        Private faultDTOField As faultDTO
        
        Private firstNameField As String
        
        Private genderField As String
        
        Private maritalStatusField As String
        
        Private middleNameField As String
        
        Private mobileNoField As String
        
        Private occupationField As String
        
        Private officeNoField As String
        
        Private pointsAccumlatedField As String
        
        Private pointsRedeemedField As String
        
        Private promotionInfobyEmailField As String
        
        Private promotionInfobySMSField As String
        
        Private referedByField As String
        
        Private resPhoneField As String
        
        Private surNameField As String
        
        Private titleField As String
        
        Private totalBalancePointField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property birthDate() As String
            Get
                Return Me.birthDateField
            End Get
            Set
                Me.birthDateField = value
                Me.RaisePropertyChanged("birthDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property cardNo() As String
            Get
                Return Me.cardNoField
            End Get
            Set
                Me.cardNoField = value
                Me.RaisePropertyChanged("cardNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property education() As String
            Get
                Return Me.educationField
            End Get
            Set
                Me.educationField = value
                Me.RaisePropertyChanged("education")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property emailId() As String
            Get
                Return Me.emailIdField
            End Get
            Set
                Me.emailIdField = value
                Me.RaisePropertyChanged("emailId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property firstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
                Me.RaisePropertyChanged("firstName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
                Me.RaisePropertyChanged("gender")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property maritalStatus() As String
            Get
                Return Me.maritalStatusField
            End Get
            Set
                Me.maritalStatusField = value
                Me.RaisePropertyChanged("maritalStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property middleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
                Me.RaisePropertyChanged("middleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property mobileNo() As String
            Get
                Return Me.mobileNoField
            End Get
            Set
                Me.mobileNoField = value
                Me.RaisePropertyChanged("mobileNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property occupation() As String
            Get
                Return Me.occupationField
            End Get
            Set
                Me.occupationField = value
                Me.RaisePropertyChanged("occupation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property officeNo() As String
            Get
                Return Me.officeNoField
            End Get
            Set
                Me.officeNoField = value
                Me.RaisePropertyChanged("officeNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property pointsAccumlated() As String
            Get
                Return Me.pointsAccumlatedField
            End Get
            Set
                Me.pointsAccumlatedField = value
                Me.RaisePropertyChanged("pointsAccumlated")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property pointsRedeemed() As String
            Get
                Return Me.pointsRedeemedField
            End Get
            Set
                Me.pointsRedeemedField = value
                Me.RaisePropertyChanged("pointsRedeemed")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property promotionInfobyEmail() As String
            Get
                Return Me.promotionInfobyEmailField
            End Get
            Set
                Me.promotionInfobyEmailField = value
                Me.RaisePropertyChanged("promotionInfobyEmail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property promotionInfobySMS() As String
            Get
                Return Me.promotionInfobySMSField
            End Get
            Set
                Me.promotionInfobySMSField = value
                Me.RaisePropertyChanged("promotionInfobySMS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property referedBy() As String
            Get
                Return Me.referedByField
            End Get
            Set
                Me.referedByField = value
                Me.RaisePropertyChanged("referedBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property resPhone() As String
            Get
                Return Me.resPhoneField
            End Get
            Set
                Me.resPhoneField = value
                Me.RaisePropertyChanged("resPhone")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property surName() As String
            Get
                Return Me.surNameField
            End Get
            Set
                Me.surNameField = value
                Me.RaisePropertyChanged("surName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
                Me.RaisePropertyChanged("title")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property totalBalancePoint() As String
            Get
                Return Me.totalBalancePointField
            End Get
            Set
                Me.totalBalancePointField = value
                Me.RaisePropertyChanged("totalBalancePoint")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/")>  _
    Partial Public Class viewCustomerResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As clpCustomerDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As clpCustomerDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class viewCustomerRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/", Order:=0)>  _
        Public viewCustomer As CLPCustomerView.viewCustomer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal viewCustomer As CLPCustomerView.viewCustomer)
            MyBase.New
            Me.viewCustomer = viewCustomer
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class viewCustomerResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://clpcustomer.webservices.spectrum.criti.com/", Order:=0)>  _
        Public viewCustomerResponse As CLPCustomerView.viewCustomerResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal viewCustomerResponse As CLPCustomerView.viewCustomerResponse)
            MyBase.New
            Me.viewCustomerResponse = viewCustomerResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ClpCustomerChannel
        Inherits CLPCustomerView.ClpCustomer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClpCustomerClient
        Inherits System.ServiceModel.ClientBase(Of CLPCustomerView.ClpCustomer)
        Implements CLPCustomerView.ClpCustomer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function CLPCustomerView_ClpCustomer_viewCustomer(ByVal request As CLPCustomerView.viewCustomerRequest) As CLPCustomerView.viewCustomerResponse1 Implements CLPCustomerView.ClpCustomer.viewCustomer
            Return MyBase.Channel.viewCustomer(request)
        End Function
        
        Public Function viewCustomer(ByVal viewCustomer1 As CLPCustomerView.viewCustomer) As CLPCustomerView.viewCustomerResponse
            Dim inValue As CLPCustomerView.viewCustomerRequest = New CLPCustomerView.viewCustomerRequest()
            inValue.viewCustomer = viewCustomer1
            Dim retVal As CLPCustomerView.viewCustomerResponse1 = CType(Me,CLPCustomerView.ClpCustomer).viewCustomer(inValue)
            Return retVal.viewCustomerResponse
        End Function
    End Class
End Namespace
