'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SpectrumUpdate
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/", ConfigurationName:="SpectrumUpdate.FOAutomaticVersionUpgradeServiceImpl")>  _
    Public Interface FOAutomaticVersionUpgradeServiceImpl
        
        'CODEGEN: Generating message contract since the operation executeService is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function executeService(ByVal request As SpectrumUpdate.executeServiceRequest) As SpectrumUpdate.executeServiceResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class executeService
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As wsRequest
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As wsRequest
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class wsRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dynaColumnsField As dynaRow
        
        Private languageCodeField As String
        
        Private soapWsHeaderField As soapWsHeader
        
        Private webMethodField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property dynaColumns() As dynaRow
            Get
                Return Me.dynaColumnsField
            End Get
            Set
                Me.dynaColumnsField = value
                Me.RaisePropertyChanged("dynaColumns")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property languageCode() As String
            Get
                Return Me.languageCodeField
            End Get
            Set
                Me.languageCodeField = value
                Me.RaisePropertyChanged("languageCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property webMethod() As String
            Get
                Return Me.webMethodField
            End Get
            Set
                Me.webMethodField = value
                Me.RaisePropertyChanged("webMethod")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class dynaRow
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dynaColumnField() As dynaColumn
        
        Private rowIDField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("dynaColumn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property dynaColumn() As dynaColumn()
            Get
                Return Me.dynaColumnField
            End Get
            Set
                Me.dynaColumnField = value
                Me.RaisePropertyChanged("dynaColumn")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property rowID() As Integer
            Get
                Return Me.rowIDField
            End Get
            Set
                Me.rowIDField = value
                Me.RaisePropertyChanged("rowID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class dynaColumn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private columnNameField As String
        
        Private columnTypeField As String
        
        Private columnValueField As String
        
        Private isDateFieldOfFromDateField As String
        
        Private isDateFieldOfToDateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property columnName() As String
            Get
                Return Me.columnNameField
            End Get
            Set
                Me.columnNameField = value
                Me.RaisePropertyChanged("columnName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property columnType() As String
            Get
                Return Me.columnTypeField
            End Get
            Set
                Me.columnTypeField = value
                Me.RaisePropertyChanged("columnType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property columnValue() As String
            Get
                Return Me.columnValueField
            End Get
            Set
                Me.columnValueField = value
                Me.RaisePropertyChanged("columnValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property isDateFieldOfFromDate() As String
            Get
                Return Me.isDateFieldOfFromDateField
            End Get
            Set
                Me.isDateFieldOfFromDateField = value
                Me.RaisePropertyChanged("isDateFieldOfFromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property isDateFieldOfToDate() As String
            Get
                Return Me.isDateFieldOfToDateField
            End Get
            Set
                Me.isDateFieldOfToDateField = value
                Me.RaisePropertyChanged("isDateFieldOfToDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class dynaTable
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private columnMetaField() As dynaColumn
        
        Private dynaRowsField() As dynaRow
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("columnMeta", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property columnMeta() As dynaColumn()
            Get
                Return Me.columnMetaField
            End Get
            Set
                Me.columnMetaField = value
                Me.RaisePropertyChanged("columnMeta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("dynaRows", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property dynaRows() As dynaRow()
            Get
                Return Me.dynaRowsField
            End Get
            Set
                Me.dynaRowsField = value
                Me.RaisePropertyChanged("dynaRows")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class wsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dynaTablesField() As dynaTable
        
        Private faultDTOsField() As faultDTO
        
        Private responseCodeField As Integer
        
        Private responseMessageField As String
        
        Private wsRequestField As wsRequest
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("dynaTables", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property dynaTables() As dynaTable()
            Get
                Return Me.dynaTablesField
            End Get
            Set
                Me.dynaTablesField = value
                Me.RaisePropertyChanged("dynaTables")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("faultDTOs", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property faultDTOs() As faultDTO()
            Get
                Return Me.faultDTOsField
            End Get
            Set
                Me.faultDTOsField = value
                Me.RaisePropertyChanged("faultDTOs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property responseCode() As Integer
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
                Me.RaisePropertyChanged("responseCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property responseMessage() As String
            Get
                Return Me.responseMessageField
            End Get
            Set
                Me.responseMessageField = value
                Me.RaisePropertyChanged("responseMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property wsRequest() As wsRequest
            Get
                Return Me.wsRequestField
            End Get
            Set
                Me.wsRequestField = value
                Me.RaisePropertyChanged("wsRequest")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class executeServiceResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As wsResponse
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As wsResponse
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
        "om/")>  _
    Partial Public Class soapWsHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class executeServiceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
            "om/", Order:=0)>  _
        Public executeService As SpectrumUpdate.executeService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal executeService As SpectrumUpdate.executeService)
            MyBase.New
            Me.executeService = executeService
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class executeServiceResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://foAutomaticVersionUpgradeServiceImpl.impl.webservice.dyna.spectrum.criti.c"& _ 
            "om/", Order:=0)>  _
        Public executeServiceResponse As SpectrumUpdate.executeServiceResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal executeServiceResponse As SpectrumUpdate.executeServiceResponse)
            MyBase.New
            Me.executeServiceResponse = executeServiceResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FOAutomaticVersionUpgradeServiceImplChannel
        Inherits SpectrumUpdate.FOAutomaticVersionUpgradeServiceImpl, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FOAutomaticVersionUpgradeServiceImplClient
        Inherits System.ServiceModel.ClientBase(Of SpectrumUpdate.FOAutomaticVersionUpgradeServiceImpl)
        Implements SpectrumUpdate.FOAutomaticVersionUpgradeServiceImpl
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SpectrumUpdate_FOAutomaticVersionUpgradeServiceImpl_executeService(ByVal request As SpectrumUpdate.executeServiceRequest) As SpectrumUpdate.executeServiceResponse1 Implements SpectrumUpdate.FOAutomaticVersionUpgradeServiceImpl.executeService
            Return MyBase.Channel.executeService(request)
        End Function
        
        Public Function executeService(ByVal executeService1 As SpectrumUpdate.executeService) As SpectrumUpdate.executeServiceResponse
            Dim inValue As SpectrumUpdate.executeServiceRequest = New SpectrumUpdate.executeServiceRequest()
            inValue.executeService = executeService1
            Dim retVal As SpectrumUpdate.executeServiceResponse1 = CType(Me,SpectrumUpdate.FOAutomaticVersionUpgradeServiceImpl).executeService(inValue)
            Return retVal.executeServiceResponse
        End Function
    End Class
End Namespace
