'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference5
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/", ConfigurationName:="ServiceReference5.AuthenticationSynchronizer")>  _
    Public Interface AuthenticationSynchronizer
        
        'CODEGEN: Generating message contract since the operation retrieveAuthenticationRecords is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function retrieveAuthenticationRecords(ByVal request As ServiceReference5.retrieveAuthenticationRecordsRequest) As ServiceReference5.retrieveAuthenticationRecordsResponse1
        
        'CODEGEN: Generating message contract since the operation saveAuthenticationRecords is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function saveAuthenticationRecords(ByVal request As ServiceReference5.saveAuthenticationRecordsRequest) As ServiceReference5.saveAuthenticationRecordsResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveAuthenticationRecords
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As wsRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As wsRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class wsRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pushOrPullField As Boolean
        
        Private pushOrPullFieldSpecified As Boolean
        
        Private siteCodeField As String
        
        Private soapWsHeaderField As soapWsHeader
        
        Private syncFromDateField As Date
        
        Private syncFromDateFieldSpecified As Boolean
        
        Private tableNameField As String
        
        Private transactionCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property pushOrPull() As Boolean
            Get
                Return Me.pushOrPullField
            End Get
            Set
                Me.pushOrPullField = value
                Me.RaisePropertyChanged("pushOrPull")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pushOrPullSpecified() As Boolean
            Get
                Return Me.pushOrPullFieldSpecified
            End Get
            Set
                Me.pushOrPullFieldSpecified = value
                Me.RaisePropertyChanged("pushOrPullSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property syncFromDate() As Date
            Get
                Return Me.syncFromDateField
            End Get
            Set
                Me.syncFromDateField = value
                Me.RaisePropertyChanged("syncFromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property syncFromDateSpecified() As Boolean
            Get
                Return Me.syncFromDateFieldSpecified
            End Get
            Set
                Me.syncFromDateFieldSpecified = value
                Me.RaisePropertyChanged("syncFromDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property tableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
                Me.RaisePropertyChanged("tableName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property transactionCode() As String
            Get
                Return Me.transactionCodeField
            End Get
            Set
                Me.transactionCodeField = value
                Me.RaisePropertyChanged("transactionCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class soapWsHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private siteCodeField As String
        
        Private storePortField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property storePort() As String
            Get
                Return Me.storePortField
            End Get
            Set
                Me.storePortField = value
                Me.RaisePropertyChanged("storePort")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncResponseDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveAuthenticationRecordsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As syncResponseDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As syncResponseDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class authenticationSaveRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private authenticationDtoField As authenticationDto
        
        Private soapWsHeaderField As soapWsHeader
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property authenticationDto() As authenticationDto
            Get
                Return Me.authenticationDtoField
            End Get
            Set
                Me.authenticationDtoField = value
                Me.RaisePropertyChanged("authenticationDto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class authenticationDto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private authRoleTransactionMapDTOField() As authRoleTransactionMapDTO
        
        Private authUserSiteRoleMapDTOField() As authUserSiteRoleMapDTO
        
        Private authUserSiteTransactionMapDTOField() As authUserSiteTransactionMapDTO
        
        Private authUsersDTOField() As authUsersDTO
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        Private mstRoleDTOField() As mstRoleDTO
        
        Private mstTransactionDTOField() As mstTransactionDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("authRoleTransactionMapDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property authRoleTransactionMapDTO() As authRoleTransactionMapDTO()
            Get
                Return Me.authRoleTransactionMapDTOField
            End Get
            Set
                Me.authRoleTransactionMapDTOField = value
                Me.RaisePropertyChanged("authRoleTransactionMapDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("authUserSiteRoleMapDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property authUserSiteRoleMapDTO() As authUserSiteRoleMapDTO()
            Get
                Return Me.authUserSiteRoleMapDTOField
            End Get
            Set
                Me.authUserSiteRoleMapDTOField = value
                Me.RaisePropertyChanged("authUserSiteRoleMapDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("authUserSiteTransactionMapDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property authUserSiteTransactionMapDTO() As authUserSiteTransactionMapDTO()
            Get
                Return Me.authUserSiteTransactionMapDTOField
            End Get
            Set
                Me.authUserSiteTransactionMapDTOField = value
                Me.RaisePropertyChanged("authUserSiteTransactionMapDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("authUsersDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property authUsersDTO() As authUsersDTO()
            Get
                Return Me.authUsersDTOField
            End Get
            Set
                Me.authUsersDTOField = value
                Me.RaisePropertyChanged("authUsersDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mstRoleDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property mstRoleDTO() As mstRoleDTO()
            Get
                Return Me.mstRoleDTOField
            End Get
            Set
                Me.mstRoleDTOField = value
                Me.RaisePropertyChanged("mstRoleDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mstTransactionDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property mstTransactionDTO() As mstTransactionDTO()
            Get
                Return Me.mstTransactionDTOField
            End Get
            Set
                Me.mstTransactionDTOField = value
                Me.RaisePropertyChanged("mstTransactionDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class authRoleTransactionMapDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private authTransactionCodeField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private roleIDField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property authTransactionCode() As String
            Get
                Return Me.authTransactionCodeField
            End Get
            Set
                Me.authTransactionCodeField = value
                Me.RaisePropertyChanged("authTransactionCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property roleID() As String
            Get
                Return Me.roleIDField
            End Get
            Set
                Me.roleIDField = value
                Me.RaisePropertyChanged("roleID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class authUserSiteRoleMapDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private gRoleidField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        Private userIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property GRoleid() As String
            Get
                Return Me.gRoleidField
            End Get
            Set
                Me.gRoleidField = value
                Me.RaisePropertyChanged("GRoleid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property userID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
                Me.RaisePropertyChanged("userID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class authUserSiteTransactionMapDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private authTransactionCodeField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private rightsField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        Private userIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property authTransactionCode() As String
            Get
                Return Me.authTransactionCodeField
            End Get
            Set
                Me.authTransactionCodeField = value
                Me.RaisePropertyChanged("authTransactionCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property rights() As String
            Get
                Return Me.rightsField
            End Get
            Set
                Me.rightsField = value
                Me.RaisePropertyChanged("rights")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property userID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
                Me.RaisePropertyChanged("userID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class authUsersDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private activeField As String
        
        Private countryCodeField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private designationField As String
        
        Private emailIdField As String
        
        Private idNumberField As String
        
        Private issalespersonField As String
        
        Private passwordField As String
        
        Private passwordChangeNextDateField As String
        
        Private passwordExpiredonField As String
        
        Private passwordUpdateDateField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        Private userIDField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property active() As String
            Get
                Return Me.activeField
            End Get
            Set
                Me.activeField = value
                Me.RaisePropertyChanged("active")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property countryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
                Me.RaisePropertyChanged("countryCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property designation() As String
            Get
                Return Me.designationField
            End Get
            Set
                Me.designationField = value
                Me.RaisePropertyChanged("designation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property emailId() As String
            Get
                Return Me.emailIdField
            End Get
            Set
                Me.emailIdField = value
                Me.RaisePropertyChanged("emailId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property idNumber() As String
            Get
                Return Me.idNumberField
            End Get
            Set
                Me.idNumberField = value
                Me.RaisePropertyChanged("idNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property issalesperson() As String
            Get
                Return Me.issalespersonField
            End Get
            Set
                Me.issalespersonField = value
                Me.RaisePropertyChanged("issalesperson")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property passwordChangeNextDate() As String
            Get
                Return Me.passwordChangeNextDateField
            End Get
            Set
                Me.passwordChangeNextDateField = value
                Me.RaisePropertyChanged("passwordChangeNextDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property passwordExpiredon() As String
            Get
                Return Me.passwordExpiredonField
            End Get
            Set
                Me.passwordExpiredonField = value
                Me.RaisePropertyChanged("passwordExpiredon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property passwordUpdateDate() As String
            Get
                Return Me.passwordUpdateDateField
            End Get
            Set
                Me.passwordUpdateDateField = value
                Me.RaisePropertyChanged("passwordUpdateDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property userID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
                Me.RaisePropertyChanged("userID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class mstRoleDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private descriptionField As String
        
        Private roleIDField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property roleID() As String
            Get
                Return Me.roleIDField
            End Get
            Set
                Me.roleIDField = value
                Me.RaisePropertyChanged("roleID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class mstTransactionDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private mainFunctionField As String
        
        Private statusField As String
        
        Private subFunctionField As String
        
        Private transactionCodeField As String
        
        Private transactionNameField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property mainFunction() As String
            Get
                Return Me.mainFunctionField
            End Get
            Set
                Me.mainFunctionField = value
                Me.RaisePropertyChanged("mainFunction")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property subFunction() As String
            Get
                Return Me.subFunctionField
            End Get
            Set
                Me.subFunctionField = value
                Me.RaisePropertyChanged("subFunction")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property transactionCode() As String
            Get
                Return Me.transactionCodeField
            End Get
            Set
                Me.transactionCodeField = value
                Me.RaisePropertyChanged("transactionCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property transactionName() As String
            Get
                Return Me.transactionNameField
            End Get
            Set
                Me.transactionNameField = value
                Me.RaisePropertyChanged("transactionName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveAuthenticationRecords
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As authenticationSaveRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As authenticationSaveRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveAuthenticationRecordsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As authenticationDto
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As authenticationDto
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveAuthenticationRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveAuthenticationRecords As ServiceReference5.retrieveAuthenticationRecords
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveAuthenticationRecords As ServiceReference5.retrieveAuthenticationRecords)
            MyBase.New
            Me.retrieveAuthenticationRecords = retrieveAuthenticationRecords
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveAuthenticationRecordsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveAuthenticationRecordsResponse As ServiceReference5.retrieveAuthenticationRecordsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveAuthenticationRecordsResponse As ServiceReference5.retrieveAuthenticationRecordsResponse)
            MyBase.New
            Me.retrieveAuthenticationRecordsResponse = retrieveAuthenticationRecordsResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveAuthenticationRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveAuthenticationRecords As ServiceReference5.saveAuthenticationRecords
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveAuthenticationRecords As ServiceReference5.saveAuthenticationRecords)
            MyBase.New
            Me.saveAuthenticationRecords = saveAuthenticationRecords
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveAuthenticationRecordsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://authentication.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveAuthenticationRecordsResponse As ServiceReference5.saveAuthenticationRecordsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveAuthenticationRecordsResponse As ServiceReference5.saveAuthenticationRecordsResponse)
            MyBase.New
            Me.saveAuthenticationRecordsResponse = saveAuthenticationRecordsResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AuthenticationSynchronizerChannel
        Inherits ServiceReference5.AuthenticationSynchronizer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AuthenticationSynchronizerClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference5.AuthenticationSynchronizer)
        Implements ServiceReference5.AuthenticationSynchronizer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference5_AuthenticationSynchronizer_retrieveAuthenticationRecords(ByVal request As ServiceReference5.retrieveAuthenticationRecordsRequest) As ServiceReference5.retrieveAuthenticationRecordsResponse1 Implements ServiceReference5.AuthenticationSynchronizer.retrieveAuthenticationRecords
            Return MyBase.Channel.retrieveAuthenticationRecords(request)
        End Function
        
        Public Function retrieveAuthenticationRecords(ByVal retrieveAuthenticationRecords1 As ServiceReference5.retrieveAuthenticationRecords) As ServiceReference5.retrieveAuthenticationRecordsResponse
            Dim inValue As ServiceReference5.retrieveAuthenticationRecordsRequest = New ServiceReference5.retrieveAuthenticationRecordsRequest()
            inValue.retrieveAuthenticationRecords = retrieveAuthenticationRecords1
            Dim retVal As ServiceReference5.retrieveAuthenticationRecordsResponse1 = CType(Me,ServiceReference5.AuthenticationSynchronizer).retrieveAuthenticationRecords(inValue)
            Return retVal.retrieveAuthenticationRecordsResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference5_AuthenticationSynchronizer_saveAuthenticationRecords(ByVal request As ServiceReference5.saveAuthenticationRecordsRequest) As ServiceReference5.saveAuthenticationRecordsResponse1 Implements ServiceReference5.AuthenticationSynchronizer.saveAuthenticationRecords
            Return MyBase.Channel.saveAuthenticationRecords(request)
        End Function
        
        Public Function saveAuthenticationRecords(ByVal saveAuthenticationRecords1 As ServiceReference5.saveAuthenticationRecords) As ServiceReference5.saveAuthenticationRecordsResponse
            Dim inValue As ServiceReference5.saveAuthenticationRecordsRequest = New ServiceReference5.saveAuthenticationRecordsRequest()
            inValue.saveAuthenticationRecords = saveAuthenticationRecords1
            Dim retVal As ServiceReference5.saveAuthenticationRecordsResponse1 = CType(Me,ServiceReference5.AuthenticationSynchronizer).saveAuthenticationRecords(inValue)
            Return retVal.saveAuthenticationRecordsResponse
        End Function
    End Class
End Namespace
