//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTreeNodeMap
    {
        public string Nodecode { get; set; }
        public string ParentNodecode { get; set; }
        public string Treecode { get; set; }
        public Nullable<decimal> ToleranceValue { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual MstArticleNode MstArticleNode { get; set; }
        public virtual MstArticleNode MstArticleNode1 { get; set; }
        public virtual MstArticleTree MstArticleTree { get; set; }
        public virtual MstArticleTree MstArticleTree1 { get; set; }
    }
}
