//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleMatrix
    {
        public string ArticleCode { get; set; } 
        public string EanCode { get; set; }
        public string CharCode { get; set; }
        public string CharValue { get; set; }
        public Nullable<bool> CharType { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string ProfileCode { get; set; }
        public Nullable<decimal> RowKey { get; set; }
    
        public virtual CharacteristicsValue CharacteristicsValue { get; set; }
        public virtual MstEAN MstEAN { get; set; }
    }
}
