//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstArticle
    {
        public MstArticle()
        {
            this.ArticleMAP = new HashSet<ArticleMAP>();
            this.ArticleNodeMap = new HashSet<ArticleNodeMap>();
            this.MstEAN = new HashSet<MstEAN>();
            this.MstVoucher = new HashSet<MstVoucher>();
            this.StockAdjustment = new HashSet<StockAdjustment>();
            this.SiteArticleTaxMapping = new HashSet<SiteArticleTaxMapping>();
            this.MstVoucher1 = new HashSet<MstVoucher>();
            this.ArticleDescInDiffLang = new HashSet<ArticleDescInDiffLang>();
            this.MasterArticleMap = new HashSet<MasterArticleMap>();
            this.MasterArticleMap1 = new HashSet<MasterArticleMap>();
            this.ArticlelblPrintDtl = new HashSet<ArticlelblPrintDtl>();
        }
    
        public string ArticleCode { get; set; }
        public string ArticalTypeCode { get; set; }
        public string ArticalCatCode { get; set; }
        public string ArticleShortName { get; set; }
        public string ArticleName { get; set; }
        public string BaseUnitofMeasure { get; set; }
        public string DistributionUnitofMeasure { get; set; }
        public string SaleUnitofMeasure { get; set; }
        public string OrderUnitofMeasure { get; set; }
        public Nullable<System.DateTime> CataloguedOn { get; set; }
        public bool ArticleActive { get; set; }
        public Nullable<bool> IssueFreeGift { get; set; }
        public Nullable<bool> ProductImage { get; set; }
        public Nullable<decimal> TotalShelfLife { get; set; }
        public Nullable<decimal> RemainingShelfLife { get; set; }
        public Nullable<bool> DecimalQtyApplicable { get; set; }
        public Nullable<bool> IsMrpOpen { get; set; }
        public Nullable<decimal> SerialNumber { get; set; }
        public Nullable<decimal> WarrantyPeriod { get; set; }
        public string ParentArt { get; set; }
        public string TreeID { get; set; }
        public string LastNodeCode { get; set; }
        public Nullable<decimal> CharProfileCode { get; set; }
        public string SupplierRef { get; set; }
        public string STLocCode { get; set; }
        public Nullable<bool> Salable { get; set; }
        public Nullable<bool> ToleranceValue { get; set; }
        public string LegacyArticleCode { get; set; }
        public string Purchaser { get; set; }
        public string IntraStatCodeEurope { get; set; }
        public string IntraStatCodeUSA { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string NetWeightUOM { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string GrossWeightUOM { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string VolumeUOM { get; set; }
        public string Style { get; set; }
        public string Season { get; set; }
        public string Theme { get; set; }
        public Nullable<bool> IsPremaman { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> NONRETUNABLE { get; set; }
        public string MaterialTypeCode { get; set; }
        public string ConsumptionUoM { get; set; }
        public Nullable<bool> isExpiry { get; set; }
        public Nullable<bool> Printable { get; set; }
        public bool IsEanAutoGenerate { get; set; }
        public bool IsBatchBarcodeAutoGenerate { get; set; }
        public Nullable<decimal> SalesUomValue { get; set; }
        public string ManufacturerCode { get; set; }
        public string BrandCode { get; set; }
        public Nullable<decimal> DistributionUomValue { get; set; }
        public string Descriptions { get; set; }
        public string Description { get; set; }
        public string HSNCode { get; set; }
    
        public virtual ICollection<ArticleMAP> ArticleMAP { get; set; }
        public virtual ICollection<ArticleNodeMap> ArticleNodeMap { get; set; }
        public virtual MstArticleTree MstArticleTree { get; set; }
        public virtual MstArticleImage MstArticleImage { get; set; }
        public virtual ICollection<MstEAN> MstEAN { get; set; }
        public virtual ICollection<MstVoucher> MstVoucher { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustment { get; set; }
        public virtual ICollection<SiteArticleTaxMapping> SiteArticleTaxMapping { get; set; }
        public virtual ICollection<MstVoucher> MstVoucher1 { get; set; }
        public virtual ICollection<ArticleDescInDiffLang> ArticleDescInDiffLang { get; set; }
        public virtual ICollection<MasterArticleMap> MasterArticleMap { get; set; }
        public virtual ICollection<MasterArticleMap> MasterArticleMap1 { get; set; }
        public virtual ICollection<ArticlelblPrintDtl> ArticlelblPrintDtl { get; set; }
    }
}
