//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstAreaCode
    {
        public MstAreaCode()
        {
            this.AuthUsers = new HashSet<AuthUsers>();
            this.AuthUsers1 = new HashSet<AuthUsers>();
            this.MstSite = new HashSet<MstSite>();
            this.MstSite1 = new HashSet<MstSite>();
        }
    
        public string AreaCode { get; set; }
        public string Description { get; set; }
        public decimal AreaType { get; set; }
        public string ParentCode { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<AuthUsers> AuthUsers { get; set; }
        public virtual ICollection<AuthUsers> AuthUsers1 { get; set; }
        public virtual ICollection<MstSite> MstSite { get; set; }
        public virtual ICollection<MstSite> MstSite1 { get; set; }
    }
}
