//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstCLPProgram
    {
        public string CLPProgramId { get; set; }
        public string CLPProgramName { get; set; }
        public string AccumlationType { get; set; }
        public string RedemptionType { get; set; }
        public Nullable<bool> PhysicalCard { get; set; }
        public Nullable<bool> CardManageByHO { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsAdvanceSaleAllowed { get; set; }
        public string ArticleCode { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> MaxLimitOnAcc { get; set; }
        public Nullable<decimal> MaxAccumulationLimit { get; set; }
        public Nullable<bool> MaxLimitOnRed { get; set; }
        public Nullable<bool> OnlyAtCreatedSite { get; set; }
        public Nullable<bool> AccWhenRed { get; set; }
        public Nullable<bool> ApplicableOnPromotion { get; set; }
        public bool IsUpgradationApplicable { get; set; }
        public bool IsUpgradationAmt { get; set; }
        public Nullable<bool> IsDeactiveInactiveAccount { get; set; }
        public Nullable<decimal> DeactiveInactiveAccountDays { get; set; }
        public Nullable<bool> IsPointsExpiry { get; set; }
        public Nullable<decimal> PointsExpiryDays { get; set; }
        public Nullable<bool> IsJoiningReward { get; set; }
        public Nullable<decimal> ValueJoiningReward { get; set; }
        public Nullable<bool> IsJoiningRewardOnEnrollment { get; set; }
        public Nullable<bool> IsRedemptionOnEnrollment { get; set; }
        public Nullable<bool> IsDayLimtOnRedemption { get; set; }
        public Nullable<decimal> ValueDayLimtRedemption { get; set; }
        public Nullable<bool> IsOnlinePasskey { get; set; }
        public Nullable<decimal> OnlinePasskeyValidity { get; set; }
        public Nullable<bool> IsPOSPasskey { get; set; }
        public Nullable<decimal> PosPasskeyValidity { get; set; }
        public Nullable<bool> IsGVAgainstLoyalty { get; set; }
        public Nullable<decimal> ValueMinPointsForRedemption { get; set; }
        public Nullable<bool> IsMinPointsForRedemption { get; set; }
    }
}
