//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstCharacteristicsProfile
    {
        public MstCharacteristicsProfile()
        {
            this.CharacteristicsProfile = new HashSet<CharacteristicsProfile>();
            this.CharacteristicsProfile1 = new HashSet<CharacteristicsProfile>();
        }
    
        public string ProfileCode { get; set; }
        public string ProfileName { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<CharacteristicsProfile> CharacteristicsProfile { get; set; }
        public virtual ICollection<CharacteristicsProfile> CharacteristicsProfile1 { get; set; }
    }
}
