//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstTransaction
    {
        public MstTransaction()
        {
            this.AuthRoleTransactionMap = new HashSet<AuthRoleTransactionMap>();
            this.AuthRoleTransactionMap1 = new HashSet<AuthRoleTransactionMap>();
            this.AuthUserSiteTransactionMap = new HashSet<AuthUserSiteTransactionMap>();
            this.AuthUserSiteTransactionMap1 = new HashSet<AuthUserSiteTransactionMap>();
            this.SiteAllowedTransactions = new HashSet<SiteAllowedTransactions>();
        }
    
        public string TransactionCode { get; set; }
        public string TransactionName { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string MainFunction { get; set; }
        public string subfunction { get; set; }
    
        public virtual ICollection<AuthRoleTransactionMap> AuthRoleTransactionMap { get; set; }
        public virtual ICollection<AuthRoleTransactionMap> AuthRoleTransactionMap1 { get; set; }
        public virtual ICollection<AuthUserSiteTransactionMap> AuthUserSiteTransactionMap { get; set; }
        public virtual ICollection<AuthUserSiteTransactionMap> AuthUserSiteTransactionMap1 { get; set; }
        public virtual ICollection<SiteAllowedTransactions> SiteAllowedTransactions { get; set; }
    }
}
