//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHdr
    {
        public OrderHdr()
        {
            this.OrderDtl = new HashSet<OrderDtl>();
        }
    
        public string SiteCode { get; set; }
        public string FinYear { get; set; }
        public string DocumentNumber { get; set; }
        public string DocumentType { get; set; }
        public System.DateTime DocDate { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<decimal> PurchaseGroupCode { get; set; }
        public string DeliverySiteCode { get; set; }
        public System.DateTime ExpectedDeliveryDt { get; set; }
        public Nullable<decimal> PaymentAfterDelDays { get; set; }
        public string AdditionalTermsNConditions { get; set; }
        public string AdditionalPaymentTerms { get; set; }
        public Nullable<decimal> DocNetValue { get; set; }
        public Nullable<decimal> DocGrossValue { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsFreezed { get; set; }
        public string ReturnReasonCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedLevel { get; set; }
        public string ApprovalLevel { get; set; }
        public string NextApprovalAt { get; set; }
        public Nullable<decimal> AmmendmentNo { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Transporter { get; set; }
        public string DocApprovalID { get; set; }
        public string ParentOrderNo { get; set; }
        public string WayBillNo { get; set; }
        public Nullable<System.DateTime> WayBillDate { get; set; }
        public string VehicleDtls { get; set; }
        public string SalesOrderRef { get; set; }
        public string YourRef { get; set; }
        public string StrategyCode { get; set; }
        public string NextApproverId { get; set; }
        public Nullable<decimal> ProcessInstanceID { get; set; }
        public Nullable<decimal> TaskInstanceID { get; set; }
        public Nullable<decimal> ProcessInstanceIDCCE { get; set; }
        public Nullable<decimal> TaskInstanceIDCCE { get; set; }
        public string StrategyStep { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public string Quarter { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string CREATEDAT { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<decimal> WarehouseCharges { get; set; }
        public Nullable<decimal> TransportCharges { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> PakingCharges { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> LocalNetValue { get; set; }
        public string driverDtls { get; set; }
        public string pickpackNumber { get; set; }
        public string ClosingRemarks { get; set; }
        public string DeliveryChallanNumber { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public string ReferenceNo { get; set; }
        public string STRType { get; set; }
        public Nullable<decimal> DocumentTaxAmount { get; set; }
        public Nullable<System.DateTime> LastSynchedTimeStamp { get; set; }
        public long Row_ID { get; set; }
        public string vadilalBillNo { get; set; }
    
        public virtual ICollection<OrderDtl> OrderDtl { get; set; }
        public virtual MstSite MstSite { get; set; }
        public virtual MstDocumentTypes MstDocumentTypes { get; set; }
    }
}
