//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInfoRecord
    {
        public string SiteCode { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<bool> IsDefaultSupplier { get; set; }
        public string ArticleCode { get; set; }
        public string EAN { get; set; }
        public Nullable<decimal> CPBaseCurr { get; set; }
        public Nullable<decimal> CPLocalCurr { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> isARSAllowed { get; set; }
        public Nullable<bool> FreezeSB { get; set; }
        public Nullable<bool> FreezeSR { get; set; }
        public Nullable<bool> FreezeIN { get; set; }
        public Nullable<bool> FreezeOB { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<decimal> SRNO { get; set; }
        public Nullable<decimal> MAP { get; set; }
        public Nullable<float> distributorMargin { get; set; }
        public Nullable<float> dealerMargin { get; set; }
        public Nullable<float> calculatedRate { get; set; }
    
        public virtual MstEAN MstEAN { get; set; }
        public virtual MstSupplier MstSupplier { get; set; }
        public virtual MstSite MstSite { get; set; }
    }
}
