//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDtl
    {
        public string SiteCode { get; set; }
        public string FinYear { get; set; }
        public string DocumentNumber { get; set; }
        public string ArticleCode { get; set; }
        public string EAN { get; set; }
        public decimal LineNumber { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string UnitofMeasure { get; set; }
        public Nullable<decimal> OpenQty { get; set; }
        public Nullable<decimal> DeliveredQty { get; set; }
        public Nullable<bool> DeliveryCompleted { get; set; }
        public Nullable<decimal> PurchaseGroupCode { get; set; }
        public string RefDocument { get; set; }
        public string RefDocumentNo { get; set; }
        public string PONo { get; set; }
        public string PoSiteCode { get; set; }
        public Nullable<decimal> PoLineNbr { get; set; }
        public string BirthListId { get; set; }
        public string SaleOrderNumber { get; set; }
        public string AllocationRule { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> NetCostPrice { get; set; }
        public Nullable<decimal> ExciseDutyAmt { get; set; }
        public Nullable<decimal> ExciseDutyRate { get; set; }
        public Nullable<decimal> PurchaseTaxAmt { get; set; }
        public Nullable<decimal> PurchaseTaxRate { get; set; }
        public Nullable<decimal> AdditionalChargeAmt { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> AdditionalChargeRate { get; set; }
        public Nullable<decimal> DocValue { get; set; }
        public Nullable<decimal> InboundQty { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> dayOpenDate { get; set; }
        public string RequestedArticle { get; set; }
        public Nullable<decimal> RequestedQty { get; set; }
        public string BaseUom { get; set; }
        public Nullable<decimal> BaseUomQty { get; set; }
        public Nullable<decimal> LocalCostPrice { get; set; }
        public Nullable<decimal> LocalDiscount { get; set; }
        public Nullable<decimal> LocalTaxAmount { get; set; }
        public Nullable<decimal> LocalNetCostPrice { get; set; }
        public Nullable<decimal> ItemTaxAmt { get; set; }
        public Nullable<decimal> LandingCostPrice { get; set; }
        public string BarCode { get; set; }
        public Nullable<System.DateTime> LastSynchedTimeStamp { get; set; }
        public string Remarks { get; set; }
        public string ReturnReasonCode { get; set; }
        public long Row_ID { get; set; }
        public Nullable<float> distributorMargin { get; set; }
        public Nullable<float> dealerMargin { get; set; }
        public Nullable<float> calculatedRate { get; set; }
    
        public virtual MstEAN MstEAN { get; set; }
        public virtual OrderHdr OrderHdr { get; set; }
    }
}
