//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxSiteDocMap
    {
        public string SiteCode { get; set; }
        public string DocumentType { get; set; }
        public string TaxCode { get; set; }
        public string TaxName { get; set; }
        public Nullable<bool> IsDocumentLevelTax { get; set; }
        public Nullable<bool> Inclusive { get; set; }
        public string Appliedon { get; set; }
        public Nullable<bool> IsPercentageValue { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<decimal> SEQUENCE { get; set; }
        public string TaxType { get; set; }
    
        public virtual MstSite MstSite { get; set; }
        public virtual MstTax MstTax { get; set; }
        public virtual MstDocumentTypes MstDocumentTypes { get; set; }
    }
}
