//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAllowedTransactions
    {
        public string TransactionCode { get; set; }
        public string SiteCode { get; set; }
        public bool Active { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual MstSite MstSite { get; set; }
        public virtual MstSite MstSite1 { get; set; }
        public virtual MstTransaction MstTransaction { get; set; }
    }
}
