//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstSite
    {
        public MstSite()
        {
            this.ArticleMAP = new HashSet<ArticleMAP>();
            this.AuthUsers = new HashSet<AuthUsers>();
            this.AuthUsers1 = new HashSet<AuthUsers>();
            this.AuthUserSiteRoleMap = new HashSet<AuthUserSiteRoleMap>();
            this.AuthUserSiteTransactionMap = new HashSet<AuthUserSiteTransactionMap>();
            this.AuthUserSiteTransactionMap1 = new HashSet<AuthUserSiteTransactionMap>();
            this.CLPProgramSiteMap = new HashSet<CLPProgramSiteMap>();
            this.MstRole = new HashSet<MstRole>();
            this.MstRole1 = new HashSet<MstRole>();
            this.MstSiteCurrancyMap = new HashSet<MstSiteCurrancyMap>();
            this.MstTender = new HashSet<MstTender>();
            this.OrderHdr = new HashSet<OrderHdr>();
            this.PurchaseInfoRecord = new HashSet<PurchaseInfoRecord>();
            this.StockAdjustment = new HashSet<StockAdjustment>();
            this.TaxSiteMapping = new HashSet<TaxSiteMapping>();
            this.SiteAllowedTransactions = new HashSet<SiteAllowedTransactions>();
            this.SiteAllowedTransactions1 = new HashSet<SiteAllowedTransactions>();
            this.TaxSiteDocMap = new HashSet<TaxSiteDocMap>();
        }
    
        public string SiteCode { get; set; }
        public string BusinessCode { get; set; }
        public string SiteShortName { get; set; }
        public string SiteOfficialName { get; set; }
        public string SiteAddressLn1 { get; set; }
        public string SiteAddressLn2 { get; set; }
        public string SiteAddressLn3 { get; set; }
        public string SitePinCode { get; set; }
        public string CityCode { get; set; }
        public string StateCode { get; set; }
        public string SiteStdCode { get; set; }
        public string SiteTelephone1 { get; set; }
        public string SiteTelephone2 { get; set; }
        public string FaxNo { get; set; }
        public string EmailId { get; set; }
        public string WebPageURL { get; set; }
        public string ContactPerson { get; set; }
        public string CountryCode { get; set; }
        public string LanguageCode { get; set; }
        public string LocalSalesTaxNo { get; set; }
        public string CentralSalesTaxNo { get; set; }
        public Nullable<System.DateTime> LocalSalesTaxDate { get; set; }
        public Nullable<System.DateTime> CentralSalesTaxDate { get; set; }
        public Nullable<decimal> SQFTArea { get; set; }
        public Nullable<bool> IsARSApplicable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsVATApplicable { get; set; }
        public Nullable<bool> IsSalesTaxApplicable { get; set; }
        public string LocalCurrancyCode { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsMAPApplicable { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string defaultean { get; set; }
        public Nullable<bool> IsWarehouseApplicable { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<bool> SisUploadFlag { get; set; }
        public Nullable<bool> IsBinApplicable { get; set; }
        public Nullable<bool> isBatchApplicable { get; set; }
        public string legacySiteCode { get; set; }
        public Nullable<bool> IsRoomCreationAllowed { get; set; }
        public Nullable<float> distributorMargin { get; set; }
        public Nullable<float> dealerMargin { get; set; }
    
        public virtual ICollection<ArticleMAP> ArticleMAP { get; set; }
        public virtual ICollection<AuthUsers> AuthUsers { get; set; }
        public virtual ICollection<AuthUsers> AuthUsers1 { get; set; }
        public virtual ICollection<AuthUserSiteRoleMap> AuthUserSiteRoleMap { get; set; }
        public virtual ICollection<AuthUserSiteTransactionMap> AuthUserSiteTransactionMap { get; set; }
        public virtual ICollection<AuthUserSiteTransactionMap> AuthUserSiteTransactionMap1 { get; set; }
        public virtual ICollection<CLPProgramSiteMap> CLPProgramSiteMap { get; set; }
        public virtual MstAreaCode MstAreaCode { get; set; }
        public virtual MstAreaCode MstAreaCode1 { get; set; }
        public virtual MstBusiness MstBusiness { get; set; }
        public virtual MstBusiness MstBusiness1 { get; set; }
        public virtual ICollection<MstRole> MstRole { get; set; }
        public virtual ICollection<MstRole> MstRole1 { get; set; }
        public virtual ICollection<MstSiteCurrancyMap> MstSiteCurrancyMap { get; set; }
        public virtual ICollection<MstTender> MstTender { get; set; }
        public virtual ICollection<OrderHdr> OrderHdr { get; set; }
        public virtual ICollection<PurchaseInfoRecord> PurchaseInfoRecord { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustment { get; set; }
        public virtual ICollection<TaxSiteMapping> TaxSiteMapping { get; set; }
        public virtual ICollection<SiteAllowedTransactions> SiteAllowedTransactions { get; set; }
        public virtual ICollection<SiteAllowedTransactions> SiteAllowedTransactions1 { get; set; }
        public virtual ICollection<TaxSiteDocMap> TaxSiteDocMap { get; set; }
    }
}
