//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUsers
    {
        public AuthUsers()
        {
            this.AuthUserSiteRoleMap = new HashSet<AuthUserSiteRoleMap>();
            this.AuthUserSiteTransactionMap = new HashSet<AuthUserSiteTransactionMap>();
            this.AuthUserSiteTransactionMap1 = new HashSet<AuthUserSiteTransactionMap>();
        }
    
        public string SiteCode { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string CountryCode { get; set; }
        public string Designation { get; set; }
        public string IDNumber { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> PasswordUpdateDate { get; set; }
        public Nullable<System.DateTime> PasswordChangeNextDate { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> PasswordExpiredon { get; set; }
        public string Active { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> issalesperson { get; set; }
        public string ParentId { get; set; }
    
        public virtual MstAreaCode MstAreaCode { get; set; }
        public virtual MstAreaCode MstAreaCode1 { get; set; }
        public virtual ICollection<AuthUserSiteRoleMap> AuthUserSiteRoleMap { get; set; }
        public virtual ICollection<AuthUserSiteTransactionMap> AuthUserSiteTransactionMap { get; set; }
        public virtual ICollection<AuthUserSiteTransactionMap> AuthUserSiteTransactionMap1 { get; set; }
        public virtual MstSite MstSite { get; set; }
        public virtual MstSite MstSite1 { get; set; }
    }
}
