'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference2
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/", ConfigurationName:="ServiceReference2.CsvFileSyncronizer")>  _
    Public Interface CsvFileSyncronizer
        
        'CODEGEN: Generating message contract since the operation syncronizeCsvFile is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function syncronizeCsvFile(ByVal request As ServiceReference2.syncronizeCsvFileRequest) As ServiceReference2.syncronizeCsvFileResponse1
        
        'CODEGEN: Generating message contract since the operation syncronizeSaveCsvFile is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function syncronizeSaveCsvFile(ByVal request As ServiceReference2.syncronizeSaveCsvFileRequest) As ServiceReference2.syncronizeSaveCsvFileResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncronizeCsvFile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As wsRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As wsRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class wsRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pushOrPullField As Boolean
        
        Private pushOrPullFieldSpecified As Boolean
        
        Private siteCodeField As String
        
        Private soapWsHeaderField As soapWsHeader
        
        Private syncFromDateField As Date
        
        Private syncFromDateFieldSpecified As Boolean
        
        Private tableNameField As String
        
        Private transactionCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property pushOrPull() As Boolean
            Get
                Return Me.pushOrPullField
            End Get
            Set
                Me.pushOrPullField = value
                Me.RaisePropertyChanged("pushOrPull")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pushOrPullSpecified() As Boolean
            Get
                Return Me.pushOrPullFieldSpecified
            End Get
            Set
                Me.pushOrPullFieldSpecified = value
                Me.RaisePropertyChanged("pushOrPullSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property syncFromDate() As Date
            Get
                Return Me.syncFromDateField
            End Get
            Set
                Me.syncFromDateField = value
                Me.RaisePropertyChanged("syncFromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property syncFromDateSpecified() As Boolean
            Get
                Return Me.syncFromDateFieldSpecified
            End Get
            Set
                Me.syncFromDateFieldSpecified = value
                Me.RaisePropertyChanged("syncFromDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property tableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
                Me.RaisePropertyChanged("tableName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property transactionCode() As String
            Get
                Return Me.transactionCodeField
            End Get
            Set
                Me.transactionCodeField = value
                Me.RaisePropertyChanged("transactionCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class soapWsHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private siteCodeField As String
        
        Private storePortField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property storePort() As String
            Get
                Return Me.storePortField
            End Get
            Set
                Me.storePortField = value
                Me.RaisePropertyChanged("storePort")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncronizeSaveCsvFileResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As syncResponseDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As syncResponseDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(imageSyncResponseDTO)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncResponseDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class imageSyncResponseDTO
        Inherits syncResponseDTO
        
        Private imageSyncDTOField() As imageSyncDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("imageSyncDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property imageSyncDTO() As imageSyncDTO()
            Get
                Return Me.imageSyncDTOField
            End Get
            Set
                Me.imageSyncDTOField = value
                Me.RaisePropertyChanged("imageSyncDTO")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class imageSyncDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fileBytesField() As Byte
        
        Private fileNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=0)>  _
        Public Property fileBytes() As Byte()
            Get
                Return Me.fileBytesField
            End Get
            Set
                Me.fileBytesField = value
                Me.RaisePropertyChanged("fileBytes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property fileName() As String
            Get
                Return Me.fileNameField
            End Get
            Set
                Me.fileNameField = value
                Me.RaisePropertyChanged("fileName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncronizeSaveCsvFile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As imageSyncDTO
        
        Private arg1Field As wsRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As imageSyncDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property arg1() As wsRequestDTO
            Get
                Return Me.arg1Field
            End Get
            Set
                Me.arg1Field = value
                Me.RaisePropertyChanged("arg1")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncronizeCsvFileResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As imageSyncResponseDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As imageSyncResponseDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class syncronizeCsvFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/", Order:=0)>  _
        Public syncronizeCsvFile As ServiceReference2.syncronizeCsvFile
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal syncronizeCsvFile As ServiceReference2.syncronizeCsvFile)
            MyBase.New
            Me.syncronizeCsvFile = syncronizeCsvFile
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class syncronizeCsvFileResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/", Order:=0)>  _
        Public syncronizeCsvFileResponse As ServiceReference2.syncronizeCsvFileResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal syncronizeCsvFileResponse As ServiceReference2.syncronizeCsvFileResponse)
            MyBase.New
            Me.syncronizeCsvFileResponse = syncronizeCsvFileResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class syncronizeSaveCsvFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/", Order:=0)>  _
        Public syncronizeSaveCsvFile As ServiceReference2.syncronizeSaveCsvFile
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal syncronizeSaveCsvFile As ServiceReference2.syncronizeSaveCsvFile)
            MyBase.New
            Me.syncronizeSaveCsvFile = syncronizeSaveCsvFile
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class syncronizeSaveCsvFileResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://csvFile.webservices.spectrum.criti.com/", Order:=0)>  _
        Public syncronizeSaveCsvFileResponse As ServiceReference2.syncronizeSaveCsvFileResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal syncronizeSaveCsvFileResponse As ServiceReference2.syncronizeSaveCsvFileResponse)
            MyBase.New
            Me.syncronizeSaveCsvFileResponse = syncronizeSaveCsvFileResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CsvFileSyncronizerChannel
        Inherits ServiceReference2.CsvFileSyncronizer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CsvFileSyncronizerClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference2.CsvFileSyncronizer)
        Implements ServiceReference2.CsvFileSyncronizer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_CsvFileSyncronizer_syncronizeCsvFile(ByVal request As ServiceReference2.syncronizeCsvFileRequest) As ServiceReference2.syncronizeCsvFileResponse1 Implements ServiceReference2.CsvFileSyncronizer.syncronizeCsvFile
            Return MyBase.Channel.syncronizeCsvFile(request)
        End Function
        
        Public Function syncronizeCsvFile(ByVal syncronizeCsvFile1 As ServiceReference2.syncronizeCsvFile) As ServiceReference2.syncronizeCsvFileResponse
            Dim inValue As ServiceReference2.syncronizeCsvFileRequest = New ServiceReference2.syncronizeCsvFileRequest()
            inValue.syncronizeCsvFile = syncronizeCsvFile1
            Dim retVal As ServiceReference2.syncronizeCsvFileResponse1 = CType(Me,ServiceReference2.CsvFileSyncronizer).syncronizeCsvFile(inValue)
            Return retVal.syncronizeCsvFileResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_CsvFileSyncronizer_syncronizeSaveCsvFile(ByVal request As ServiceReference2.syncronizeSaveCsvFileRequest) As ServiceReference2.syncronizeSaveCsvFileResponse1 Implements ServiceReference2.CsvFileSyncronizer.syncronizeSaveCsvFile
            Return MyBase.Channel.syncronizeSaveCsvFile(request)
        End Function
        
        Public Function syncronizeSaveCsvFile(ByVal syncronizeSaveCsvFile1 As ServiceReference2.syncronizeSaveCsvFile) As ServiceReference2.syncronizeSaveCsvFileResponse
            Dim inValue As ServiceReference2.syncronizeSaveCsvFileRequest = New ServiceReference2.syncronizeSaveCsvFileRequest()
            inValue.syncronizeSaveCsvFile = syncronizeSaveCsvFile1
            Dim retVal As ServiceReference2.syncronizeSaveCsvFileResponse1 = CType(Me,ServiceReference2.CsvFileSyncronizer).syncronizeSaveCsvFile(inValue)
            Return retVal.syncronizeSaveCsvFileResponse
        End Function
    End Class
End Namespace
