'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ArticleStockServices
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/", ConfigurationName:="ArticleStockServices.ArticleStockBalancesSynchronizer")>  _
    Public Interface ArticleStockBalancesSynchronizer
        
        'CODEGEN: Generating message contract since the operation retrieveArticleStockBalancesRecords is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function retrieveArticleStockBalancesRecords(ByVal request As ArticleStockServices.retrieveArticleStockBalancesRecordsRequest) As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse1
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="", ReplyAction:="*")>  _
        Function BeginretrieveArticleStockBalancesRecords(ByVal request As ArticleStockServices.retrieveArticleStockBalancesRecordsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndretrieveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse1
        
        'CODEGEN: Generating message contract since the operation saveArticleStockBalancesRecords is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function saveArticleStockBalancesRecords(ByVal request As ArticleStockServices.saveArticleStockBalancesRecordsRequest) As ArticleStockServices.saveArticleStockBalancesRecordsResponse1
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="", ReplyAction:="*")>  _
        Function BeginsaveArticleStockBalancesRecords(ByVal request As ArticleStockServices.saveArticleStockBalancesRecordsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndsaveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As ArticleStockServices.saveArticleStockBalancesRecordsResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveArticleStockBalancesRecords
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As articleStockBalancesRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As articleStockBalancesRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class articleStockBalancesRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleCodeField As String
        
        Private eanField As String
        
        Private pushOrPullField As Boolean
        
        Private pushOrPullFieldSpecified As Boolean
        
        Private siteCodeField As String
        
        Private soapWsHeaderField As soapWsHeader
        
        Private syncFromDateField As Date
        
        Private syncFromDateFieldSpecified As Boolean
        
        Private transactionCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property articleCode() As String
            Get
                Return Me.articleCodeField
            End Get
            Set
                Me.articleCodeField = value
                Me.RaisePropertyChanged("articleCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property ean() As String
            Get
                Return Me.eanField
            End Get
            Set
                Me.eanField = value
                Me.RaisePropertyChanged("ean")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property pushOrPull() As Boolean
            Get
                Return Me.pushOrPullField
            End Get
            Set
                Me.pushOrPullField = value
                Me.RaisePropertyChanged("pushOrPull")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pushOrPullSpecified() As Boolean
            Get
                Return Me.pushOrPullFieldSpecified
            End Get
            Set
                Me.pushOrPullFieldSpecified = value
                Me.RaisePropertyChanged("pushOrPullSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property syncFromDate() As Date
            Get
                Return Me.syncFromDateField
            End Get
            Set
                Me.syncFromDateField = value
                Me.RaisePropertyChanged("syncFromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property syncFromDateSpecified() As Boolean
            Get
                Return Me.syncFromDateFieldSpecified
            End Get
            Set
                Me.syncFromDateFieldSpecified = value
                Me.RaisePropertyChanged("syncFromDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property transactionCode() As String
            Get
                Return Me.transactionCodeField
            End Get
            Set
                Me.transactionCodeField = value
                Me.RaisePropertyChanged("transactionCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class soapWsHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private siteCodeField As String
        
        Private storePortField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property storePort() As String
            Get
                Return Me.storePortField
            End Get
            Set
                Me.storePortField = value
                Me.RaisePropertyChanged("storePort")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncResponseDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveArticleStockBalancesRecordsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As syncResponseDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As syncResponseDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class articleStockBalancesSaveRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleStockBalancesDtosField As articleStockBalancesDtos
        
        Private soapWsHeaderField As soapWsHeader
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property articleStockBalancesDtos() As articleStockBalancesDtos
            Get
                Return Me.articleStockBalancesDtosField
            End Get
            Set
                Me.articleStockBalancesDtosField = value
                Me.RaisePropertyChanged("articleStockBalancesDtos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class articleStockBalancesDtos
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleStockBalancesDTOField() As articleStockBalancesDTO
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("articleStockBalancesDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property articleStockBalancesDTO() As articleStockBalancesDTO()
            Get
                Return Me.articleStockBalancesDTOField
            End Get
            Set
                Me.articleStockBalancesDTOField = value
                Me.RaisePropertyChanged("articleStockBalancesDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class articleStockBalancesDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleCodeField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private damagedQtyField As String
        
        Private eANField As String
        
        Private inTrasnsitQtyField As String
        
        Private nextAvailableDateField As String
        
        Private nonSaleableQtyField As String
        
        Private onOrderQtyField As String
        
        Private physicalQtyField As String
        
        Private reservedQtyField As String
        
        Private siteCodeField As String
        
        Private siteNameField As String
        
        Private statusField As String
        
        Private stockStatusField As String
        
        Private totalARSQtyField As String
        
        Private totalPhysicalNonSaleableQtyField As String
        
        Private totalPhysicalSaleableQtyField As String
        
        Private totalSaleableQtyField As String
        
        Private totalVirtualNonSaleableQtyField As String
        
        Private uOMField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property articleCode() As String
            Get
                Return Me.articleCodeField
            End Get
            Set
                Me.articleCodeField = value
                Me.RaisePropertyChanged("articleCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property damagedQty() As String
            Get
                Return Me.damagedQtyField
            End Get
            Set
                Me.damagedQtyField = value
                Me.RaisePropertyChanged("damagedQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property EAN() As String
            Get
                Return Me.eANField
            End Get
            Set
                Me.eANField = value
                Me.RaisePropertyChanged("EAN")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property inTrasnsitQty() As String
            Get
                Return Me.inTrasnsitQtyField
            End Get
            Set
                Me.inTrasnsitQtyField = value
                Me.RaisePropertyChanged("inTrasnsitQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property nextAvailableDate() As String
            Get
                Return Me.nextAvailableDateField
            End Get
            Set
                Me.nextAvailableDateField = value
                Me.RaisePropertyChanged("nextAvailableDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property nonSaleableQty() As String
            Get
                Return Me.nonSaleableQtyField
            End Get
            Set
                Me.nonSaleableQtyField = value
                Me.RaisePropertyChanged("nonSaleableQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property onOrderQty() As String
            Get
                Return Me.onOrderQtyField
            End Get
            Set
                Me.onOrderQtyField = value
                Me.RaisePropertyChanged("onOrderQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property physicalQty() As String
            Get
                Return Me.physicalQtyField
            End Get
            Set
                Me.physicalQtyField = value
                Me.RaisePropertyChanged("physicalQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property reservedQty() As String
            Get
                Return Me.reservedQtyField
            End Get
            Set
                Me.reservedQtyField = value
                Me.RaisePropertyChanged("reservedQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property siteName() As String
            Get
                Return Me.siteNameField
            End Get
            Set
                Me.siteNameField = value
                Me.RaisePropertyChanged("siteName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property stockStatus() As String
            Get
                Return Me.stockStatusField
            End Get
            Set
                Me.stockStatusField = value
                Me.RaisePropertyChanged("stockStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property totalARSQty() As String
            Get
                Return Me.totalARSQtyField
            End Get
            Set
                Me.totalARSQtyField = value
                Me.RaisePropertyChanged("totalARSQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property totalPhysicalNonSaleableQty() As String
            Get
                Return Me.totalPhysicalNonSaleableQtyField
            End Get
            Set
                Me.totalPhysicalNonSaleableQtyField = value
                Me.RaisePropertyChanged("totalPhysicalNonSaleableQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property totalPhysicalSaleableQty() As String
            Get
                Return Me.totalPhysicalSaleableQtyField
            End Get
            Set
                Me.totalPhysicalSaleableQtyField = value
                Me.RaisePropertyChanged("totalPhysicalSaleableQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property totalSaleableQty() As String
            Get
                Return Me.totalSaleableQtyField
            End Get
            Set
                Me.totalSaleableQtyField = value
                Me.RaisePropertyChanged("totalSaleableQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property totalVirtualNonSaleableQty() As String
            Get
                Return Me.totalVirtualNonSaleableQtyField
            End Get
            Set
                Me.totalVirtualNonSaleableQtyField = value
                Me.RaisePropertyChanged("totalVirtualNonSaleableQty")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=21)>  _
        Public Property UOM() As String
            Get
                Return Me.uOMField
            End Get
            Set
                Me.uOMField = value
                Me.RaisePropertyChanged("UOM")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=22)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=23)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=24)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveArticleStockBalancesRecords
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As articleStockBalancesSaveRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As articleStockBalancesSaveRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveArticleStockBalancesRecordsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As articleStockBalancesDtos
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As articleStockBalancesDtos
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveArticleStockBalancesRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveArticleStockBalancesRecords As ArticleStockServices.retrieveArticleStockBalancesRecords
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveArticleStockBalancesRecords As ArticleStockServices.retrieveArticleStockBalancesRecords)
            MyBase.New
            Me.retrieveArticleStockBalancesRecords = retrieveArticleStockBalancesRecords
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveArticleStockBalancesRecordsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveArticleStockBalancesRecordsResponse As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveArticleStockBalancesRecordsResponse As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse)
            MyBase.New
            Me.retrieveArticleStockBalancesRecordsResponse = retrieveArticleStockBalancesRecordsResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveArticleStockBalancesRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveArticleStockBalancesRecords As ArticleStockServices.saveArticleStockBalancesRecords
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveArticleStockBalancesRecords As ArticleStockServices.saveArticleStockBalancesRecords)
            MyBase.New
            Me.saveArticleStockBalancesRecords = saveArticleStockBalancesRecords
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveArticleStockBalancesRecordsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://articleStockBalances.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveArticleStockBalancesRecordsResponse As ArticleStockServices.saveArticleStockBalancesRecordsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveArticleStockBalancesRecordsResponse As ArticleStockServices.saveArticleStockBalancesRecordsResponse)
            MyBase.New
            Me.saveArticleStockBalancesRecordsResponse = saveArticleStockBalancesRecordsResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ArticleStockBalancesSynchronizerChannel
        Inherits ArticleStockServices.ArticleStockBalancesSynchronizer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class retrieveArticleStockBalancesRecordsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ArticleStockServices.retrieveArticleStockBalancesRecordsResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class saveArticleStockBalancesRecordsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As ArticleStockServices.saveArticleStockBalancesRecordsResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ArticleStockServices.saveArticleStockBalancesRecordsResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ArticleStockBalancesSynchronizerClient
        Inherits System.ServiceModel.ClientBase(Of ArticleStockServices.ArticleStockBalancesSynchronizer)
        Implements ArticleStockServices.ArticleStockBalancesSynchronizer
        
        Private onBeginretrieveArticleStockBalancesRecordsDelegate As BeginOperationDelegate
        
        Private onEndretrieveArticleStockBalancesRecordsDelegate As EndOperationDelegate
        
        Private onretrieveArticleStockBalancesRecordsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginsaveArticleStockBalancesRecordsDelegate As BeginOperationDelegate
        
        Private onEndsaveArticleStockBalancesRecordsDelegate As EndOperationDelegate
        
        Private onsaveArticleStockBalancesRecordsCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event retrieveArticleStockBalancesRecordsCompleted As System.EventHandler(Of retrieveArticleStockBalancesRecordsCompletedEventArgs)
        
        Public Event saveArticleStockBalancesRecordsCompleted As System.EventHandler(Of saveArticleStockBalancesRecordsCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ArticleStockServices_ArticleStockBalancesSynchronizer_retrieveArticleStockBalancesRecords(ByVal request As ArticleStockServices.retrieveArticleStockBalancesRecordsRequest) As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse1 Implements ArticleStockServices.ArticleStockBalancesSynchronizer.retrieveArticleStockBalancesRecords
            Return MyBase.Channel.retrieveArticleStockBalancesRecords(request)
        End Function
        
        Public Function retrieveArticleStockBalancesRecords(ByVal retrieveArticleStockBalancesRecords1 As ArticleStockServices.retrieveArticleStockBalancesRecords) As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse
            Dim inValue As ArticleStockServices.retrieveArticleStockBalancesRecordsRequest = New ArticleStockServices.retrieveArticleStockBalancesRecordsRequest()
            inValue.retrieveArticleStockBalancesRecords = retrieveArticleStockBalancesRecords1
            Dim retVal As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse1 = CType(Me,ArticleStockServices.ArticleStockBalancesSynchronizer).retrieveArticleStockBalancesRecords(inValue)
            Return retVal.retrieveArticleStockBalancesRecordsResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ArticleStockServices_ArticleStockBalancesSynchronizer_BeginretrieveArticleStockBalancesRecords(ByVal request As ArticleStockServices.retrieveArticleStockBalancesRecordsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ArticleStockServices.ArticleStockBalancesSynchronizer.BeginretrieveArticleStockBalancesRecords
            Return MyBase.Channel.BeginretrieveArticleStockBalancesRecords(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginretrieveArticleStockBalancesRecords(ByVal retrieveArticleStockBalancesRecords As ArticleStockServices.retrieveArticleStockBalancesRecords, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As ArticleStockServices.retrieveArticleStockBalancesRecordsRequest = New ArticleStockServices.retrieveArticleStockBalancesRecordsRequest()
            inValue.retrieveArticleStockBalancesRecords = retrieveArticleStockBalancesRecords
            Return CType(Me,ArticleStockServices.ArticleStockBalancesSynchronizer).BeginretrieveArticleStockBalancesRecords(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ArticleStockServices_ArticleStockBalancesSynchronizer_EndretrieveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse1 Implements ArticleStockServices.ArticleStockBalancesSynchronizer.EndretrieveArticleStockBalancesRecords
            Return MyBase.Channel.EndretrieveArticleStockBalancesRecords(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndretrieveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse
            Dim retVal As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse1 = CType(Me,ArticleStockServices.ArticleStockBalancesSynchronizer).EndretrieveArticleStockBalancesRecords(result)
            Return retVal.retrieveArticleStockBalancesRecordsResponse
        End Function
        
        Private Function OnBeginretrieveArticleStockBalancesRecords(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim retrieveArticleStockBalancesRecords As ArticleStockServices.retrieveArticleStockBalancesRecords = CType(inValues(0),ArticleStockServices.retrieveArticleStockBalancesRecords)
            Return Me.BeginretrieveArticleStockBalancesRecords(retrieveArticleStockBalancesRecords, callback, asyncState)
        End Function
        
        Private Function OnEndretrieveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As ArticleStockServices.retrieveArticleStockBalancesRecordsResponse = Me.EndretrieveArticleStockBalancesRecords(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnretrieveArticleStockBalancesRecordsCompleted(ByVal state As Object)
            If (Not (Me.retrieveArticleStockBalancesRecordsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent retrieveArticleStockBalancesRecordsCompleted(Me, New retrieveArticleStockBalancesRecordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub retrieveArticleStockBalancesRecordsAsync(ByVal retrieveArticleStockBalancesRecords As ArticleStockServices.retrieveArticleStockBalancesRecords)
            Me.retrieveArticleStockBalancesRecordsAsync(retrieveArticleStockBalancesRecords, Nothing)
        End Sub
        
        Public Overloads Sub retrieveArticleStockBalancesRecordsAsync(ByVal retrieveArticleStockBalancesRecords As ArticleStockServices.retrieveArticleStockBalancesRecords, ByVal userState As Object)
            If (Me.onBeginretrieveArticleStockBalancesRecordsDelegate Is Nothing) Then
                Me.onBeginretrieveArticleStockBalancesRecordsDelegate = AddressOf Me.OnBeginretrieveArticleStockBalancesRecords
            End If
            If (Me.onEndretrieveArticleStockBalancesRecordsDelegate Is Nothing) Then
                Me.onEndretrieveArticleStockBalancesRecordsDelegate = AddressOf Me.OnEndretrieveArticleStockBalancesRecords
            End If
            If (Me.onretrieveArticleStockBalancesRecordsCompletedDelegate Is Nothing) Then
                Me.onretrieveArticleStockBalancesRecordsCompletedDelegate = AddressOf Me.OnretrieveArticleStockBalancesRecordsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginretrieveArticleStockBalancesRecordsDelegate, New Object() {retrieveArticleStockBalancesRecords}, Me.onEndretrieveArticleStockBalancesRecordsDelegate, Me.onretrieveArticleStockBalancesRecordsCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ArticleStockServices_ArticleStockBalancesSynchronizer_saveArticleStockBalancesRecords(ByVal request As ArticleStockServices.saveArticleStockBalancesRecordsRequest) As ArticleStockServices.saveArticleStockBalancesRecordsResponse1 Implements ArticleStockServices.ArticleStockBalancesSynchronizer.saveArticleStockBalancesRecords
            Return MyBase.Channel.saveArticleStockBalancesRecords(request)
        End Function
        
        Public Function saveArticleStockBalancesRecords(ByVal saveArticleStockBalancesRecords1 As ArticleStockServices.saveArticleStockBalancesRecords) As ArticleStockServices.saveArticleStockBalancesRecordsResponse
            Dim inValue As ArticleStockServices.saveArticleStockBalancesRecordsRequest = New ArticleStockServices.saveArticleStockBalancesRecordsRequest()
            inValue.saveArticleStockBalancesRecords = saveArticleStockBalancesRecords1
            Dim retVal As ArticleStockServices.saveArticleStockBalancesRecordsResponse1 = CType(Me,ArticleStockServices.ArticleStockBalancesSynchronizer).saveArticleStockBalancesRecords(inValue)
            Return retVal.saveArticleStockBalancesRecordsResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ArticleStockServices_ArticleStockBalancesSynchronizer_BeginsaveArticleStockBalancesRecords(ByVal request As ArticleStockServices.saveArticleStockBalancesRecordsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ArticleStockServices.ArticleStockBalancesSynchronizer.BeginsaveArticleStockBalancesRecords
            Return MyBase.Channel.BeginsaveArticleStockBalancesRecords(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginsaveArticleStockBalancesRecords(ByVal saveArticleStockBalancesRecords As ArticleStockServices.saveArticleStockBalancesRecords, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As ArticleStockServices.saveArticleStockBalancesRecordsRequest = New ArticleStockServices.saveArticleStockBalancesRecordsRequest()
            inValue.saveArticleStockBalancesRecords = saveArticleStockBalancesRecords
            Return CType(Me,ArticleStockServices.ArticleStockBalancesSynchronizer).BeginsaveArticleStockBalancesRecords(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ArticleStockServices_ArticleStockBalancesSynchronizer_EndsaveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As ArticleStockServices.saveArticleStockBalancesRecordsResponse1 Implements ArticleStockServices.ArticleStockBalancesSynchronizer.EndsaveArticleStockBalancesRecords
            Return MyBase.Channel.EndsaveArticleStockBalancesRecords(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndsaveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As ArticleStockServices.saveArticleStockBalancesRecordsResponse
            Dim retVal As ArticleStockServices.saveArticleStockBalancesRecordsResponse1 = CType(Me,ArticleStockServices.ArticleStockBalancesSynchronizer).EndsaveArticleStockBalancesRecords(result)
            Return retVal.saveArticleStockBalancesRecordsResponse
        End Function
        
        Private Function OnBeginsaveArticleStockBalancesRecords(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim saveArticleStockBalancesRecords As ArticleStockServices.saveArticleStockBalancesRecords = CType(inValues(0),ArticleStockServices.saveArticleStockBalancesRecords)
            Return Me.BeginsaveArticleStockBalancesRecords(saveArticleStockBalancesRecords, callback, asyncState)
        End Function
        
        Private Function OnEndsaveArticleStockBalancesRecords(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As ArticleStockServices.saveArticleStockBalancesRecordsResponse = Me.EndsaveArticleStockBalancesRecords(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnsaveArticleStockBalancesRecordsCompleted(ByVal state As Object)
            If (Not (Me.saveArticleStockBalancesRecordsCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent saveArticleStockBalancesRecordsCompleted(Me, New saveArticleStockBalancesRecordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub saveArticleStockBalancesRecordsAsync(ByVal saveArticleStockBalancesRecords As ArticleStockServices.saveArticleStockBalancesRecords)
            Me.saveArticleStockBalancesRecordsAsync(saveArticleStockBalancesRecords, Nothing)
        End Sub
        
        Public Overloads Sub saveArticleStockBalancesRecordsAsync(ByVal saveArticleStockBalancesRecords As ArticleStockServices.saveArticleStockBalancesRecords, ByVal userState As Object)
            If (Me.onBeginsaveArticleStockBalancesRecordsDelegate Is Nothing) Then
                Me.onBeginsaveArticleStockBalancesRecordsDelegate = AddressOf Me.OnBeginsaveArticleStockBalancesRecords
            End If
            If (Me.onEndsaveArticleStockBalancesRecordsDelegate Is Nothing) Then
                Me.onEndsaveArticleStockBalancesRecordsDelegate = AddressOf Me.OnEndsaveArticleStockBalancesRecords
            End If
            If (Me.onsaveArticleStockBalancesRecordsCompletedDelegate Is Nothing) Then
                Me.onsaveArticleStockBalancesRecordsCompletedDelegate = AddressOf Me.OnsaveArticleStockBalancesRecordsCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginsaveArticleStockBalancesRecordsDelegate, New Object() {saveArticleStockBalancesRecords}, Me.onEndsaveArticleStockBalancesRecordsDelegate, Me.onsaveArticleStockBalancesRecordsCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
