'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference3
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/", ConfigurationName:="ServiceReference3.BillingSynchronizer")>  _
    Public Interface BillingSynchronizer
        
        'CODEGEN: Generating message contract since the operation retrieveBillingDetails is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function retrieveBillingDetails(ByVal request As ServiceReference3.retrieveBillingDetailsRequest) As ServiceReference3.retrieveBillingDetailsResponse1
        
        'CODEGEN: Generating message contract since the operation saveBillingDetails is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function saveBillingDetails(ByVal request As ServiceReference3.saveBillingDetailsRequest) As ServiceReference3.saveBillingDetailsResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveBillingDetails
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As wsRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As wsRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class wsRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pushOrPullField As Boolean
        
        Private pushOrPullFieldSpecified As Boolean
        
        Private siteCodeField As String
        
        Private soapWsHeaderField As soapWsHeader
        
        Private syncFromDateField As Date
        
        Private syncFromDateFieldSpecified As Boolean
        
        Private tableNameField As String
        
        Private transactionCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property pushOrPull() As Boolean
            Get
                Return Me.pushOrPullField
            End Get
            Set
                Me.pushOrPullField = value
                Me.RaisePropertyChanged("pushOrPull")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pushOrPullSpecified() As Boolean
            Get
                Return Me.pushOrPullFieldSpecified
            End Get
            Set
                Me.pushOrPullFieldSpecified = value
                Me.RaisePropertyChanged("pushOrPullSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property syncFromDate() As Date
            Get
                Return Me.syncFromDateField
            End Get
            Set
                Me.syncFromDateField = value
                Me.RaisePropertyChanged("syncFromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property syncFromDateSpecified() As Boolean
            Get
                Return Me.syncFromDateFieldSpecified
            End Get
            Set
                Me.syncFromDateFieldSpecified = value
                Me.RaisePropertyChanged("syncFromDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property tableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
                Me.RaisePropertyChanged("tableName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property transactionCode() As String
            Get
                Return Me.transactionCodeField
            End Get
            Set
                Me.transactionCodeField = value
                Me.RaisePropertyChanged("transactionCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class soapWsHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private siteCodeField As String
        
        Private storePortField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property storePort() As String
            Get
                Return Me.storePortField
            End Get
            Set
                Me.storePortField = value
                Me.RaisePropertyChanged("storePort")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncResponseDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveBillingDetailsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As syncResponseDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As syncResponseDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class billingSaveRequestDto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private billingDTOsField As billingDTOs
        
        Private soapWsHeaderField As soapWsHeader
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property billingDTOs() As billingDTOs
            Get
                Return Me.billingDTOsField
            End Get
            Set
                Me.billingDTOsField = value
                Me.RaisePropertyChanged("billingDTOs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class billingDTOs
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private buttonArticleDTOField() As buttonArticleDTO
        
        Private buttonGroupDTOField() As buttonGroupDTO
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private cmReceiptTenderDtlDTOField() As cmReceiptTenderDtlDTO
        
        Private cmTenderValidationConfigDTOField() As cmTenderValidationConfigDTO
        
        Private faultDTOField As faultDTO
        
        Private mstReceiptLabelsDTOField() As mstReceiptLabelsDTO
        
        Private mstSalesPersonDTOField() As mstSalesPersonDTO
        
        Private posDeviceProfileDTOField() As posDeviceProfileDTO
        
        Private printingDetailDTOField() As printingDetailDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("buttonArticleDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property buttonArticleDTO() As buttonArticleDTO()
            Get
                Return Me.buttonArticleDTOField
            End Get
            Set
                Me.buttonArticleDTOField = value
                Me.RaisePropertyChanged("buttonArticleDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("buttonGroupDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property buttonGroupDTO() As buttonGroupDTO()
            Get
                Return Me.buttonGroupDTOField
            End Get
            Set
                Me.buttonGroupDTOField = value
                Me.RaisePropertyChanged("buttonGroupDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("cmReceiptTenderDtlDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property cmReceiptTenderDtlDTO() As cmReceiptTenderDtlDTO()
            Get
                Return Me.cmReceiptTenderDtlDTOField
            End Get
            Set
                Me.cmReceiptTenderDtlDTOField = value
                Me.RaisePropertyChanged("cmReceiptTenderDtlDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("cmTenderValidationConfigDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property cmTenderValidationConfigDTO() As cmTenderValidationConfigDTO()
            Get
                Return Me.cmTenderValidationConfigDTOField
            End Get
            Set
                Me.cmTenderValidationConfigDTOField = value
                Me.RaisePropertyChanged("cmTenderValidationConfigDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mstReceiptLabelsDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property mstReceiptLabelsDTO() As mstReceiptLabelsDTO()
            Get
                Return Me.mstReceiptLabelsDTOField
            End Get
            Set
                Me.mstReceiptLabelsDTOField = value
                Me.RaisePropertyChanged("mstReceiptLabelsDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mstSalesPersonDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property mstSalesPersonDTO() As mstSalesPersonDTO()
            Get
                Return Me.mstSalesPersonDTOField
            End Get
            Set
                Me.mstSalesPersonDTOField = value
                Me.RaisePropertyChanged("mstSalesPersonDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("posDeviceProfileDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property posDeviceProfileDTO() As posDeviceProfileDTO()
            Get
                Return Me.posDeviceProfileDTOField
            End Get
            Set
                Me.posDeviceProfileDTOField = value
                Me.RaisePropertyChanged("posDeviceProfileDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("printingDetailDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=9)>  _
        Public Property printingDetailDTO() As printingDetailDTO()
            Get
                Return Me.printingDetailDTOField
            End Get
            Set
                Me.printingDetailDTOField = value
                Me.RaisePropertyChanged("printingDetailDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class buttonArticleDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleCodeField As String
        
        Private articleNameField As String
        
        Private buttonArticleIdField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private groupIdField As String
        
        Private isActiveField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property articleCode() As String
            Get
                Return Me.articleCodeField
            End Get
            Set
                Me.articleCodeField = value
                Me.RaisePropertyChanged("articleCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property articleName() As String
            Get
                Return Me.articleNameField
            End Get
            Set
                Me.articleNameField = value
                Me.RaisePropertyChanged("articleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property buttonArticleId() As String
            Get
                Return Me.buttonArticleIdField
            End Get
            Set
                Me.buttonArticleIdField = value
                Me.RaisePropertyChanged("buttonArticleId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property groupId() As String
            Get
                Return Me.groupIdField
            End Get
            Set
                Me.groupIdField = value
                Me.RaisePropertyChanged("groupId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property isActive() As String
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
                Me.RaisePropertyChanged("isActive")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class buttonGroupDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private groupIdField As String
        
        Private groupNameField As String
        
        Private isActiveField As String
        
        Private parentGroupIdField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property groupId() As String
            Get
                Return Me.groupIdField
            End Get
            Set
                Me.groupIdField = value
                Me.RaisePropertyChanged("groupId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property groupName() As String
            Get
                Return Me.groupNameField
            End Get
            Set
                Me.groupNameField = value
                Me.RaisePropertyChanged("groupName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property isActive() As String
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
                Me.RaisePropertyChanged("isActive")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property parentGroupId() As String
            Get
                Return Me.parentGroupIdField
            End Get
            Set
                Me.parentGroupIdField = value
                Me.RaisePropertyChanged("parentGroupId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class cmReceiptTenderDtlDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private billNoField As String
        
        Private cMRecptLinenoField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private fldLabelField As String
        
        Private fldValueField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private tenderTypeCodeField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property billNo() As String
            Get
                Return Me.billNoField
            End Get
            Set
                Me.billNoField = value
                Me.RaisePropertyChanged("billNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property CMRecptLineno() As String
            Get
                Return Me.cMRecptLinenoField
            End Get
            Set
                Me.cMRecptLinenoField = value
                Me.RaisePropertyChanged("CMRecptLineno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property fldLabel() As String
            Get
                Return Me.fldLabelField
            End Get
            Set
                Me.fldLabelField = value
                Me.RaisePropertyChanged("fldLabel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property fldValue() As String
            Get
                Return Me.fldValueField
            End Get
            Set
                Me.fldValueField = value
                Me.RaisePropertyChanged("fldValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property tenderTypeCode() As String
            Get
                Return Me.tenderTypeCodeField
            End Get
            Set
                Me.tenderTypeCodeField = value
                Me.RaisePropertyChanged("tenderTypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class cmTenderValidationConfigDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private fldLabelField As String
        
        Private fldValueDataTypeField As String
        
        Private statusField As String
        
        Private tenderHeadCodeField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        Private validatiionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property fldLabel() As String
            Get
                Return Me.fldLabelField
            End Get
            Set
                Me.fldLabelField = value
                Me.RaisePropertyChanged("fldLabel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property fldValueDataType() As String
            Get
                Return Me.fldValueDataTypeField
            End Get
            Set
                Me.fldValueDataTypeField = value
                Me.RaisePropertyChanged("fldValueDataType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property tenderHeadCode() As String
            Get
                Return Me.tenderHeadCodeField
            End Get
            Set
                Me.tenderHeadCodeField = value
                Me.RaisePropertyChanged("tenderHeadCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property validatiion() As String
            Get
                Return Me.validatiionField
            End Get
            Set
                Me.validatiionField = value
                Me.RaisePropertyChanged("validatiion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class mstReceiptLabelsDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private labelDateField As String
        
        Private labelNo_1Field As String
        
        Private labelNo_2Field As String
        
        Private labelNo_3Field As String
        
        Private labelNo_4Field As String
        
        Private statusField As String
        
        Private tenderHeadCodeField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property labelDate() As String
            Get
                Return Me.labelDateField
            End Get
            Set
                Me.labelDateField = value
                Me.RaisePropertyChanged("labelDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property labelNo_1() As String
            Get
                Return Me.labelNo_1Field
            End Get
            Set
                Me.labelNo_1Field = value
                Me.RaisePropertyChanged("labelNo_1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property labelNo_2() As String
            Get
                Return Me.labelNo_2Field
            End Get
            Set
                Me.labelNo_2Field = value
                Me.RaisePropertyChanged("labelNo_2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property labelNo_3() As String
            Get
                Return Me.labelNo_3Field
            End Get
            Set
                Me.labelNo_3Field = value
                Me.RaisePropertyChanged("labelNo_3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property labelNo_4() As String
            Get
                Return Me.labelNo_4Field
            End Get
            Set
                Me.labelNo_4Field = value
                Me.RaisePropertyChanged("labelNo_4")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property tenderHeadCode() As String
            Get
                Return Me.tenderHeadCodeField
            End Get
            Set
                Me.tenderHeadCodeField = value
                Me.RaisePropertyChanged("tenderHeadCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class mstSalesPersonDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private empcodeField As String
        
        Private salesAreaField As String
        
        Private salesPersonFullNameField As String
        
        Private salesPersonNameField As String
        
        Private salesSectionField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property empcode() As String
            Get
                Return Me.empcodeField
            End Get
            Set
                Me.empcodeField = value
                Me.RaisePropertyChanged("empcode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property salesArea() As String
            Get
                Return Me.salesAreaField
            End Get
            Set
                Me.salesAreaField = value
                Me.RaisePropertyChanged("salesArea")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property salesPersonFullName() As String
            Get
                Return Me.salesPersonFullNameField
            End Get
            Set
                Me.salesPersonFullNameField = value
                Me.RaisePropertyChanged("salesPersonFullName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property salesPersonName() As String
            Get
                Return Me.salesPersonNameField
            End Get
            Set
                Me.salesPersonNameField = value
                Me.RaisePropertyChanged("salesPersonName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property salesSection() As String
            Get
                Return Me.salesSectionField
            End Get
            Set
                Me.salesSectionField = value
                Me.RaisePropertyChanged("salesSection")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class posDeviceProfileDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private deviceNameField As String
        
        Private deviceTypeField As String
        
        Private driverTypeField As String
        
        Private isConfiguredField As String
        
        Private logicalNameField As String
        
        Private siteCodeField As String
        
        Private statusField As String
        
        Private terminalIdField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property deviceName() As String
            Get
                Return Me.deviceNameField
            End Get
            Set
                Me.deviceNameField = value
                Me.RaisePropertyChanged("deviceName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property deviceType() As String
            Get
                Return Me.deviceTypeField
            End Get
            Set
                Me.deviceTypeField = value
                Me.RaisePropertyChanged("deviceType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property driverType() As String
            Get
                Return Me.driverTypeField
            End Get
            Set
                Me.driverTypeField = value
                Me.RaisePropertyChanged("driverType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property isConfigured() As String
            Get
                Return Me.isConfiguredField
            End Get
            Set
                Me.isConfiguredField = value
                Me.RaisePropertyChanged("isConfigured")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property logicalName() As String
            Get
                Return Me.logicalNameField
            End Get
            Set
                Me.logicalNameField = value
                Me.RaisePropertyChanged("logicalName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property terminalId() As String
            Get
                Return Me.terminalIdField
            End Get
            Set
                Me.terminalIdField = value
                Me.RaisePropertyChanged("terminalId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class printingDetailDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private alignField As String
        
        Private boldField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private documentTypeField As String
        
        Private heightField As String
        
        Private receiptTextField As String
        
        Private sequenceNoField As String
        
        Private siteCodeField As String
        
        Private srnoField As String
        
        Private statusField As String
        
        Private topBottomField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        Private widthField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property align() As String
            Get
                Return Me.alignField
            End Get
            Set
                Me.alignField = value
                Me.RaisePropertyChanged("align")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property bold() As String
            Get
                Return Me.boldField
            End Get
            Set
                Me.boldField = value
                Me.RaisePropertyChanged("bold")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property documentType() As String
            Get
                Return Me.documentTypeField
            End Get
            Set
                Me.documentTypeField = value
                Me.RaisePropertyChanged("documentType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property height() As String
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
                Me.RaisePropertyChanged("height")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property receiptText() As String
            Get
                Return Me.receiptTextField
            End Get
            Set
                Me.receiptTextField = value
                Me.RaisePropertyChanged("receiptText")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property sequenceNo() As String
            Get
                Return Me.sequenceNoField
            End Get
            Set
                Me.sequenceNoField = value
                Me.RaisePropertyChanged("sequenceNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property srno() As String
            Get
                Return Me.srnoField
            End Get
            Set
                Me.srnoField = value
                Me.RaisePropertyChanged("srno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property topBottom() As String
            Get
                Return Me.topBottomField
            End Get
            Set
                Me.topBottomField = value
                Me.RaisePropertyChanged("topBottom")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property width() As String
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
                Me.RaisePropertyChanged("width")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveBillingDetails
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As billingSaveRequestDto
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As billingSaveRequestDto
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveBillingDetailsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As billingDTOs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As billingDTOs
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveBillingDetailsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveBillingDetails As ServiceReference3.retrieveBillingDetails
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveBillingDetails As ServiceReference3.retrieveBillingDetails)
            MyBase.New
            Me.retrieveBillingDetails = retrieveBillingDetails
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveBillingDetailsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveBillingDetailsResponse As ServiceReference3.retrieveBillingDetailsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveBillingDetailsResponse As ServiceReference3.retrieveBillingDetailsResponse)
            MyBase.New
            Me.retrieveBillingDetailsResponse = retrieveBillingDetailsResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveBillingDetailsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveBillingDetails As ServiceReference3.saveBillingDetails
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveBillingDetails As ServiceReference3.saveBillingDetails)
            MyBase.New
            Me.saveBillingDetails = saveBillingDetails
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveBillingDetailsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://billing.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveBillingDetailsResponse As ServiceReference3.saveBillingDetailsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveBillingDetailsResponse As ServiceReference3.saveBillingDetailsResponse)
            MyBase.New
            Me.saveBillingDetailsResponse = saveBillingDetailsResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface BillingSynchronizerChannel
        Inherits ServiceReference3.BillingSynchronizer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BillingSynchronizerClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference3.BillingSynchronizer)
        Implements ServiceReference3.BillingSynchronizer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference3_BillingSynchronizer_retrieveBillingDetails(ByVal request As ServiceReference3.retrieveBillingDetailsRequest) As ServiceReference3.retrieveBillingDetailsResponse1 Implements ServiceReference3.BillingSynchronizer.retrieveBillingDetails
            Return MyBase.Channel.retrieveBillingDetails(request)
        End Function
        
        Public Function retrieveBillingDetails(ByVal retrieveBillingDetails1 As ServiceReference3.retrieveBillingDetails) As ServiceReference3.retrieveBillingDetailsResponse
            Dim inValue As ServiceReference3.retrieveBillingDetailsRequest = New ServiceReference3.retrieveBillingDetailsRequest()
            inValue.retrieveBillingDetails = retrieveBillingDetails1
            Dim retVal As ServiceReference3.retrieveBillingDetailsResponse1 = CType(Me,ServiceReference3.BillingSynchronizer).retrieveBillingDetails(inValue)
            Return retVal.retrieveBillingDetailsResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference3_BillingSynchronizer_saveBillingDetails(ByVal request As ServiceReference3.saveBillingDetailsRequest) As ServiceReference3.saveBillingDetailsResponse1 Implements ServiceReference3.BillingSynchronizer.saveBillingDetails
            Return MyBase.Channel.saveBillingDetails(request)
        End Function
        
        Public Function saveBillingDetails(ByVal saveBillingDetails1 As ServiceReference3.saveBillingDetails) As ServiceReference3.saveBillingDetailsResponse
            Dim inValue As ServiceReference3.saveBillingDetailsRequest = New ServiceReference3.saveBillingDetailsRequest()
            inValue.saveBillingDetails = saveBillingDetails1
            Dim retVal As ServiceReference3.saveBillingDetailsResponse1 = CType(Me,ServiceReference3.BillingSynchronizer).saveBillingDetails(inValue)
            Return retVal.saveBillingDetailsResponse
        End Function
    End Class
End Namespace
