'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/", ConfigurationName:="ServiceReference1.UomSynchronizer")>  _
    Public Interface UomSynchronizer
        
        'CODEGEN: Generating message contract since the operation retrieveUomRecords is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function retrieveUomRecords(ByVal request As ServiceReference1.retrieveUomRecordsRequest) As ServiceReference1.retrieveUomRecordsResponse1
        
        'CODEGEN: Generating message contract since the operation saveUomRecords is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function saveUomRecords(ByVal request As ServiceReference1.saveUomRecordsRequest) As ServiceReference1.saveUomRecordsResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveUomRecords
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As wsRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As wsRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class wsRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pushOrPullField As Boolean
        
        Private pushOrPullFieldSpecified As Boolean
        
        Private siteCodeField As String
        
        Private soapWsHeaderField As soapWsHeader
        
        Private syncFromDateField As Date
        
        Private syncFromDateFieldSpecified As Boolean
        
        Private tableNameField As String
        
        Private transactionCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property pushOrPull() As Boolean
            Get
                Return Me.pushOrPullField
            End Get
            Set
                Me.pushOrPullField = value
                Me.RaisePropertyChanged("pushOrPull")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pushOrPullSpecified() As Boolean
            Get
                Return Me.pushOrPullFieldSpecified
            End Get
            Set
                Me.pushOrPullFieldSpecified = value
                Me.RaisePropertyChanged("pushOrPullSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property syncFromDate() As Date
            Get
                Return Me.syncFromDateField
            End Get
            Set
                Me.syncFromDateField = value
                Me.RaisePropertyChanged("syncFromDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property syncFromDateSpecified() As Boolean
            Get
                Return Me.syncFromDateFieldSpecified
            End Get
            Set
                Me.syncFromDateFieldSpecified = value
                Me.RaisePropertyChanged("syncFromDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property tableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
                Me.RaisePropertyChanged("tableName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property transactionCode() As String
            Get
                Return Me.transactionCodeField
            End Get
            Set
                Me.transactionCodeField = value
                Me.RaisePropertyChanged("transactionCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class soapWsHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private passwordField As String
        
        Private siteCodeField As String
        
        Private storePortField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property siteCode() As String
            Get
                Return Me.siteCodeField
            End Get
            Set
                Me.siteCodeField = value
                Me.RaisePropertyChanged("siteCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property storePort() As String
            Get
                Return Me.storePortField
            End Get
            Set
                Me.storePortField = value
                Me.RaisePropertyChanged("storePort")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("userName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class syncResponseDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class faultDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private businessErrorField As String
        
        Private faultLevelField As String
        
        Private faultStackTraceField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property businessError() As String
            Get
                Return Me.businessErrorField
            End Get
            Set
                Me.businessErrorField = value
                Me.RaisePropertyChanged("businessError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property faultLevel() As String
            Get
                Return Me.faultLevelField
            End Get
            Set
                Me.faultLevelField = value
                Me.RaisePropertyChanged("faultLevel")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultStackTrace() As String
            Get
                Return Me.faultStackTraceField
            End Get
            Set
                Me.faultStackTraceField = value
                Me.RaisePropertyChanged("faultStackTrace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveUomRecordsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As syncResponseDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As syncResponseDTO
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class uomSaveRequestDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private soapWsHeaderField As soapWsHeader
        
        Private uomdtOsField As uomdtOs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property soapWsHeader() As soapWsHeader
            Get
                Return Me.soapWsHeaderField
            End Get
            Set
                Me.soapWsHeaderField = value
                Me.RaisePropertyChanged("soapWsHeader")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property uomdtOs() As uomdtOs
            Get
                Return Me.uomdtOsField
            End Get
            Set
                Me.uomdtOsField = value
                Me.RaisePropertyChanged("uomdtOs")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class uomdtOs
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleUOMDTOField() As articleUOMDTO
        
        Private calendarField As Date
        
        Private calendarFieldSpecified As Boolean
        
        Private faultDTOField As faultDTO
        
        Private mstUoMDTOField() As mstUoMDTO
        
        Private mstUoMTypeDTOField() As mstUoMTypeDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("articleUOMDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property articleUOMDTO() As articleUOMDTO()
            Get
                Return Me.articleUOMDTOField
            End Get
            Set
                Me.articleUOMDTOField = value
                Me.RaisePropertyChanged("articleUOMDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property calendar() As Date
            Get
                Return Me.calendarField
            End Get
            Set
                Me.calendarField = value
                Me.RaisePropertyChanged("calendar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property calendarSpecified() As Boolean
            Get
                Return Me.calendarFieldSpecified
            End Get
            Set
                Me.calendarFieldSpecified = value
                Me.RaisePropertyChanged("calendarSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property faultDTO() As faultDTO
            Get
                Return Me.faultDTOField
            End Get
            Set
                Me.faultDTOField = value
                Me.RaisePropertyChanged("faultDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mstUoMDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property mstUoMDTO() As mstUoMDTO()
            Get
                Return Me.mstUoMDTOField
            End Get
            Set
                Me.mstUoMDTOField = value
                Me.RaisePropertyChanged("mstUoMDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mstUoMTypeDTO", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property mstUoMTypeDTO() As mstUoMTypeDTO()
            Get
                Return Me.mstUoMTypeDTOField
            End Get
            Set
                Me.mstUoMTypeDTOField = value
                Me.RaisePropertyChanged("mstUoMTypeDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class articleUOMDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private articleCodeField As String
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private defaultUomField As String
        
        Private divisorField As String
        
        Private isDivisorField As String
        
        Private statusField As String
        
        Private uomCodeField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property articleCode() As String
            Get
                Return Me.articleCodeField
            End Get
            Set
                Me.articleCodeField = value
                Me.RaisePropertyChanged("articleCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property defaultUom() As String
            Get
                Return Me.defaultUomField
            End Get
            Set
                Me.defaultUomField = value
                Me.RaisePropertyChanged("defaultUom")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property divisor() As String
            Get
                Return Me.divisorField
            End Get
            Set
                Me.divisorField = value
                Me.RaisePropertyChanged("divisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property isDivisor() As String
            Get
                Return Me.isDivisorField
            End Get
            Set
                Me.isDivisorField = value
                Me.RaisePropertyChanged("isDivisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property uomCode() As String
            Get
                Return Me.uomCodeField
            End Get
            Set
                Me.uomCodeField = value
                Me.RaisePropertyChanged("uomCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class mstUoMDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private statusField As String
        
        Private uomField As String
        
        Private uomCodeField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property uom() As String
            Get
                Return Me.uomField
            End Get
            Set
                Me.uomField = value
                Me.RaisePropertyChanged("uom")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property uomCode() As String
            Get
                Return Me.uomCodeField
            End Get
            Set
                Me.uomCodeField = value
                Me.RaisePropertyChanged("uomCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class mstUoMTypeDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private createdatField As String
        
        Private createdbyField As String
        
        Private createdonField As String
        
        Private statusField As String
        
        Private uomtypeField As String
        
        Private uomtypeCodeField As String
        
        Private updatedatField As String
        
        Private updatedbyField As String
        
        Private updatedonField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property createdat() As String
            Get
                Return Me.createdatField
            End Get
            Set
                Me.createdatField = value
                Me.RaisePropertyChanged("createdat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property createdby() As String
            Get
                Return Me.createdbyField
            End Get
            Set
                Me.createdbyField = value
                Me.RaisePropertyChanged("createdby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property createdon() As String
            Get
                Return Me.createdonField
            End Get
            Set
                Me.createdonField = value
                Me.RaisePropertyChanged("createdon")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property uomtype() As String
            Get
                Return Me.uomtypeField
            End Get
            Set
                Me.uomtypeField = value
                Me.RaisePropertyChanged("uomtype")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property uomtypeCode() As String
            Get
                Return Me.uomtypeCodeField
            End Get
            Set
                Me.uomtypeCodeField = value
                Me.RaisePropertyChanged("uomtypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property updatedat() As String
            Get
                Return Me.updatedatField
            End Get
            Set
                Me.updatedatField = value
                Me.RaisePropertyChanged("updatedat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property updatedby() As String
            Get
                Return Me.updatedbyField
            End Get
            Set
                Me.updatedbyField = value
                Me.RaisePropertyChanged("updatedby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property updatedon() As String
            Get
                Return Me.updatedonField
            End Get
            Set
                Me.updatedonField = value
                Me.RaisePropertyChanged("updatedon")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class saveUomRecords
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arg0Field As uomSaveRequestDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property arg0() As uomSaveRequestDTO
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
                Me.RaisePropertyChanged("arg0")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/")>  _
    Partial Public Class retrieveUomRecordsResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnField As uomdtOs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property [return]() As uomdtOs
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
                Me.RaisePropertyChanged("return")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveUomRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveUomRecords As ServiceReference1.retrieveUomRecords
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveUomRecords As ServiceReference1.retrieveUomRecords)
            MyBase.New
            Me.retrieveUomRecords = retrieveUomRecords
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveUomRecordsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/", Order:=0)>  _
        Public retrieveUomRecordsResponse As ServiceReference1.retrieveUomRecordsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal retrieveUomRecordsResponse As ServiceReference1.retrieveUomRecordsResponse)
            MyBase.New
            Me.retrieveUomRecordsResponse = retrieveUomRecordsResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveUomRecordsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveUomRecords As ServiceReference1.saveUomRecords
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveUomRecords As ServiceReference1.saveUomRecords)
            MyBase.New
            Me.saveUomRecords = saveUomRecords
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class saveUomRecordsResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://uom.webservices.spectrum.criti.com/", Order:=0)>  _
        Public saveUomRecordsResponse As ServiceReference1.saveUomRecordsResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal saveUomRecordsResponse As ServiceReference1.saveUomRecordsResponse)
            MyBase.New
            Me.saveUomRecordsResponse = saveUomRecordsResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UomSynchronizerChannel
        Inherits ServiceReference1.UomSynchronizer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UomSynchronizerClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.UomSynchronizer)
        Implements ServiceReference1.UomSynchronizer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UomSynchronizer_retrieveUomRecords(ByVal request As ServiceReference1.retrieveUomRecordsRequest) As ServiceReference1.retrieveUomRecordsResponse1 Implements ServiceReference1.UomSynchronizer.retrieveUomRecords
            Return MyBase.Channel.retrieveUomRecords(request)
        End Function
        
        Public Function retrieveUomRecords(ByVal retrieveUomRecords1 As ServiceReference1.retrieveUomRecords) As ServiceReference1.retrieveUomRecordsResponse
            Dim inValue As ServiceReference1.retrieveUomRecordsRequest = New ServiceReference1.retrieveUomRecordsRequest()
            inValue.retrieveUomRecords = retrieveUomRecords1
            Dim retVal As ServiceReference1.retrieveUomRecordsResponse1 = CType(Me,ServiceReference1.UomSynchronizer).retrieveUomRecords(inValue)
            Return retVal.retrieveUomRecordsResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_UomSynchronizer_saveUomRecords(ByVal request As ServiceReference1.saveUomRecordsRequest) As ServiceReference1.saveUomRecordsResponse1 Implements ServiceReference1.UomSynchronizer.saveUomRecords
            Return MyBase.Channel.saveUomRecords(request)
        End Function
        
        Public Function saveUomRecords(ByVal saveUomRecords1 As ServiceReference1.saveUomRecords) As ServiceReference1.saveUomRecordsResponse
            Dim inValue As ServiceReference1.saveUomRecordsRequest = New ServiceReference1.saveUomRecordsRequest()
            inValue.saveUomRecords = saveUomRecords1
            Dim retVal As ServiceReference1.saveUomRecordsResponse1 = CType(Me,ServiceReference1.UomSynchronizer).saveUomRecords(inValue)
            Return retVal.saveUomRecordsResponse
        End Function
    End Class
End Namespace
