//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstVoucher
    {
        public string VoucherCode { get; set; }
        public string VoucherDesc { get; set; }
        public string VourcherType { get; set; }
        public string ArticleCode { get; set; }
        public bool allowAnyDeno { get; set; }
        public bool IsPrePrinted { get; set; }
        public Nullable<bool> DoesVoucherExpire { get; set; }
        public Nullable<int> ExpiryAfterDays { get; set; }
        public Nullable<bool> IsAdvanceSaleAllowed { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual MstTenderType MstTenderType { get; set; }
        public virtual MstTenderType MstTenderType1 { get; set; }
        public virtual MstArticle MstArticle { get; set; }
        public virtual MstArticle MstArticle1 { get; set; }
    }
}
