//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstCurrency
    {
        public MstCurrency()
        {
            this.MstSiteCurrancyMap = new HashSet<MstSiteCurrancyMap>();
        }
    
        public string CurrencyCode { get; set; }
        public string CurrencyDescription { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<bool> EMUCurrency { get; set; }
        public Nullable<decimal> RealisedGain { get; set; }
        public Nullable<decimal> RealisedLoss { get; set; }
        public Nullable<decimal> UNRealisedGain { get; set; }
        public Nullable<decimal> UNRealisedLoss { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<MstSiteCurrancyMap> MstSiteCurrancyMap { get; set; }
    }
}
