//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstEAN
    {
        public MstEAN()
        {
            this.ArticleMatrix = new HashSet<ArticleMatrix>();
            this.ArticleReplenishment = new HashSet<ArticleReplenishment>();
            this.ArticleReplenishment1 = new HashSet<ArticleReplenishment>();
            this.PurchaseInfoRecord = new HashSet<PurchaseInfoRecord>();
            this.StockAdjustment = new HashSet<StockAdjustment>();
            this.OrderDtl = new HashSet<OrderDtl>();
        }
    
        public string ArticleCode { get; set; }
        public string EAN { get; set; }
        public string Discription { get; set; }
        public string UOMCode { get; set; }
        public string UOMTypeCode { get; set; }
        public Nullable<bool> DefaultEAN { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<ArticleMatrix> ArticleMatrix { get; set; }
        public virtual ICollection<ArticleReplenishment> ArticleReplenishment { get; set; }
        public virtual ICollection<ArticleReplenishment> ArticleReplenishment1 { get; set; }
        public virtual ICollection<PurchaseInfoRecord> PurchaseInfoRecord { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustment { get; set; }
        public virtual ICollection<OrderDtl> OrderDtl { get; set; }
        public virtual MstArticle MstArticle { get; set; }
    }
}
