//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstArticleTree
    {
        public MstArticleTree()
        {
            this.ArticleTreeNodeMap = new HashSet<ArticleTreeNodeMap>();
            this.ArticleTreeNodeMap1 = new HashSet<ArticleTreeNodeMap>();
            this.MstArticleNode = new HashSet<MstArticleNode>();
            this.MstArticleTreeLevel = new HashSet<MstArticleTreeLevel>();
            this.MstArticleTreeLevel1 = new HashSet<MstArticleTreeLevel>();
            this.MstArticle = new HashSet<MstArticle>();
        }
    
        public string TreeCode { get; set; }
        public string TreeName { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<ArticleTreeNodeMap> ArticleTreeNodeMap { get; set; }
        public virtual ICollection<ArticleTreeNodeMap> ArticleTreeNodeMap1 { get; set; }
        public virtual ICollection<MstArticleNode> MstArticleNode { get; set; }
        public virtual ICollection<MstArticleTreeLevel> MstArticleTreeLevel { get; set; }
        public virtual ICollection<MstArticleTreeLevel> MstArticleTreeLevel1 { get; set; }
        public virtual ICollection<MstArticle> MstArticle { get; set; }
    }
}
