//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxSiteMapping
    {
        public string Taxcode { get; set; }
        public string Sitecode { get; set; }
        public Nullable<bool> Defaultsite { get; set; }
        public string CreatedAT { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string updatedat { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual MstTax MstTax { get; set; }
        public virtual MstSite MstSite { get; set; }
    }
}
