//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstMaterialArticleMap
    {
        public string SiteCode { get; set; }
        public string ArticleCode { get; set; }
        public string MaterialType { get; set; }
        public string MaterialId { get; set; }
        public string MaterialValue { get; set; }
        public string CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual MstMaterial MstMaterial { get; set; }
    }
}
