//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralCodeMst
    {
        public string CodeType { get; set; }
        public string Code { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public Nullable<bool> Status { get; set; }
        public int IsSysParameter { get; set; }
        public string Created_By { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedAt { get; set; }
        public string UpdateAt { get; set; }
        public string SiteCode { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
