//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstTender
    {
        public string TenderHeadCode { get; set; }
        public string SiteCode { get; set; }
        public string TenderHeadName { get; set; }
        public string TenderType { get; set; }
        public string Positive_Negative { get; set; }
        public Nullable<decimal> MaxNo { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> MinBillValue { get; set; }
        public string DefaultValue { get; set; }
        public string ProgramId { get; set; }
        public string CREATEDAT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string UPDATEDAT { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    
        public virtual MstTenderType MstTenderType { get; set; }
        public virtual MstSite MstSite { get; set; }
    }
}
