'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CashMemoComboDtl
    Inherits BasePrintModel

    Public Property SiteCode As String
    Public Property FinYear As String
    Public Property BillNo As String
    Public Property ComboLineNumber As String
    Public Property BillLineNo As String
    Public Property EAN As String
    Public Property ComboArticleCode As String
    Public Property ArticleCode As String
    Public Property SellingPrice As String
    Public Property NetSellingPrice As String
    Public Property CostPrice As String
    Public Property GrossAmt As String
    Public Property NetAmount As String
    Public Property Quantity As String
    Public Property TotalDiscount As String
    Public Property ArticleName As String
End Class
